services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_URL: ${APP_URL}
        VITE_API_PREFIX: ${VITE_API_PREFIX:-}
        S3_ENDPOINT: ${S3_ENDPOINT}
    image: ocop-storefront:production
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
    env_file:
      - .env
