export const POST_ERROR_CODES = {
  NOT_FOUND: 'POST_001',
  PLATFORM_NOT_FOUND: 'POST_002',
  PLATFORM_IN_USE: 'POST_003',
  CATEGORY_NOT_FOUND: 'POST_004',
  CATEGORY_INVALID_PARENT: 'POST_005',
  CATEGORY_IN_USE: 'POST_006',
} as const
