import type { MediaLabels } from './types'

export function createMediaLabels(t: (key: string) => string): MediaLabels {
  const key = (name: string) => t(`manager.${name}`)

  return {
    allFiles: key('allFiles'),
    unclassified: key('unclassified'),
    banner: key('banner'),
    logo: key('logo'),
    documents: key('documents'),
    other: key('other'),
    trash: key('trash'),
    allFilesBreadcrumb: key('allFilesBreadcrumb'),
    search: key('search'),
    newFolder: key('newFolder'),
    upload: key('upload'),
    allTypes: key('allTypes'),
    allSizes: key('allSizes'),
    uploadedAt: key('uploadedAt'),
    filter: key('filter'),
    list: key('list'),
    grid: key('grid'),
    fileInfo: key('fileInfo'),
    selectFile: key('selectFile'),
    filePath: key('filePath'),
    fileSize: key('fileSize'),
    imageSize: key('imageSize'),
    uploadedBy: key('uploadedBy'),
    actions: key('actions'),
    download: key('download'),
    rename: key('rename'),
    move: key('move'),
    copyLink: key('copyLink'),
    edit: key('edit'),
    delete: key('delete'),
    noFiles: key('noFiles'),
    usedStorage: key('usedStorage'),
    manageStorage: key('manageStorage'),
    fileType: key('fileType'),
    folder: key('folder'),
    file: key('file'),
    loadMore: key('loadMore'),
    selectMultiple: key('selectMultiple'),
    cancelSelect: key('cancelSelect'),
    deleteSelected: key('deleteSelected'),
    selectedCount: key('selectedCount'),
  }
}
