export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_001',
  ACCOUNT_UNVERIFIED: 'AUTH_002',
  USER_ALREADY_EXISTS: 'AUTH_003',
  EMAIL_NOT_FOUND: 'AUTH_004',
  RESET_TOKEN_INVALID: 'AUTH_005',
  VERIFICATION_USER_NOT_FOUND: 'AUTH_006',
  VERIFICATION_LINK_INVALID: 'AUTH_007',
  AUTHENTICATION_REQUIRED: 'AUTH_008',
  AUTHORIZATION_REQUIRED: 'AUTH_009',
  INVALID_PERMISSION_CODE: 'AUTH_032',
} as const
