export const USER_ERROR_CODES = {
  NOT_FOUND: 'USER_001',
  ALREADY_EXISTS: 'USER_002',
  CONTACT_ALREADY_EXISTS: 'USER_010',
  SUPER_ADMIN_PROTECTED: 'USER_021',
  PERMISSION_NOT_FOUND: 'USER_022',
  CANNOT_REMOVE_OWN_ADMIN_PERMISSION: 'USER_023',
  CANNOT_BLOCK_SELF: 'USER_024',
  EMPTY_SELECTION: 'USER_025',
} as const

export const USER_ROLE_ERROR_CODES = {
  NOT_FOUND: 'USER_ROLE_001',
  IN_USE: 'USER_ROLE_004',
  CODE_EXISTS: 'USER_ROLE_005',
  SYSTEM_PROTECTED: 'USER_ROLE_006',
} as const
