import { useTranslation } from 'react-i18next'
import { Check, Server, Trash2, Upload } from 'lucide-react'
import type { VpsPlan } from '../../types/vps'

const inputClass = 'h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100'
const Field = ({ label, children, required = false }: { label: string; children: React.ReactNode; required?: boolean }) => <label className="block space-y-1.5"><span className="text-xs font-semibold text-slate-700">{label}{required && <span className="text-red-500"> *</span>}</span>{children}</label>

export function VpsPackageForm({ initialPlan }: { initialPlan?: VpsPlan }) {
  const { t } = useTranslation('catalog')
  const tabs = ['basicInfo', 'configuration', 'pricing', 'visibility']
  return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div className="flex items-center justify-between"><h2 className="text-xl font-bold text-[#11184c]">{t('vps.form.createTitle')}</h2><button type="button" className="text-slate-400"><Trash2 className="size-4" /></button></div><div className="mt-5 grid grid-cols-4 border-b border-slate-200 text-xs font-medium">{tabs.map((tab, index) => <button key={tab} type="button" className={index === 0 ? 'border-b-2 border-blue-600 px-1 pb-3 text-blue-600' : 'border-b-2 border-transparent px-1 pb-3 text-slate-500'}>{t(`vps.form.${tab}`)}</button>)}</div><div className="space-y-4 pt-5"><Field label={t('vps.form.name')} required><input className={inputClass} defaultValue={initialPlan?.name ?? ''} placeholder={t('vps.form.namePlaceholder')} /></Field><Field label={t('vps.form.shortDescription')} required><textarea className="min-h-20 w-full resize-none rounded-lg border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" defaultValue={t('vps.form.shortDescriptionValue')} /></Field><Field label={t('vps.form.category')}><select className={inputClass}><option>{t('vps.categories.vps')}</option><option>{t('vps.categories.hosting')}</option></select></Field><Field label={t('vps.form.tag')}><input className={inputClass} defaultValue={t('vps.form.tagValue')} /></Field><Field label={t('vps.form.defaultProvider')} required><select className={inputClass}><option>{t('vps.providers.a')}</option><option>{t('vps.providers.b')}</option></select></Field><Field label={t('vps.form.image')}><div className="flex items-center gap-3"><div className="flex h-20 w-28 items-center justify-center rounded-lg bg-blue-50 text-blue-500"><Server className="size-10" /></div><button type="button" className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold"><Upload className="size-4" /> {t('vps.form.changeImage')}</button></div></Field><Field label={t('vps.form.visibility')}><div className="flex gap-5 text-sm"><label className="flex items-center gap-2"><input type="radio" defaultChecked name="status" /> {t('vps.form.visible')}</label><label className="flex items-center gap-2"><input type="radio" name="status" /> {t('vps.form.hidden')}</label></div></Field></div><div className="mt-6 flex gap-2 border-t border-slate-100 pt-4"><button type="button" className="h-10 flex-1 rounded-lg border border-slate-200 text-sm font-semibold text-slate-600">{t('vps.form.cancel')}</button><button type="button" className="h-10 flex-1 rounded-lg border border-slate-200 text-sm font-semibold text-slate-600">{t('vps.form.saveDraft')}</button><button type="button" className="h-10 flex-1 rounded-lg bg-blue-600 text-sm font-semibold text-white hover:bg-blue-700">{t('vps.form.next')} <Check className="ml-1 inline size-4" /></button></div></div>
}
