import { MoreHorizontal, Server } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { cn } from '@/utils/utils'
import type { VpsPlan } from '../../types/vps'

export function VpsPlansTable({ plans, onSelect, onToggle }: { plans: VpsPlan[]; onSelect: (plan: VpsPlan) => void; onToggle: (name: string) => void }) {
  const { t } = useTranslation('catalog')
  const locations: Record<string, string> = { 'Việt Nam': 'vietnam', Singapore: 'singapore', 'Nhật Bản': 'japan', 'Hoa Kỳ': 'usa', Đức: 'germany' }
  return <><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-slate-50 text-[11px] font-semibold text-slate-600"><tr><th className="px-3 py-3"><input type="checkbox" /></th><th>#</th><th>{t('vps.table.name')}</th><th>{t('vps.table.configuration')}</th><th>{t('vps.table.price')}</th><th>{t('vps.table.provider')}</th><th>{t('vps.table.location')}</th><th>{t('vps.table.status')}</th><th>{t('vps.table.actions')}</th></tr></thead><tbody className="divide-y divide-slate-100">{plans.map((plan, index) => <tr key={plan.name} className="hover:bg-blue-50/40"><td className="px-3 py-3"><input type="checkbox" /></td><td className="text-slate-500">{index + 1}</td><td className="px-3 py-3"><button type="button" onClick={() => onSelect(plan)} className="text-left"><span className="block font-bold text-[#11184c]">{plan.name} {index === 0 && <span className="rounded bg-emerald-100 px-1.5 py-0.5 text-[10px] text-emerald-600">{t('vps.table.popular')}</span>}</span><span className="text-[11px] text-slate-500">{plan.description}</span></button></td><td className="whitespace-nowrap leading-5 text-slate-500">{plan.cpu}<br />{plan.ram}<br />{plan.disk}</td><td className="whitespace-nowrap font-bold text-[#11184c]">{plan.price}<br /><span className="font-normal text-slate-500">{t('vps.table.perMonth')}</span></td><td><span className={cn('mr-1 inline-flex size-6 items-center justify-center rounded-full text-white', plan.color)}><Server className="size-3" /></span>{plan.provider}</td><td className="whitespace-nowrap">{plan.country} {t(`vps.locations.${locations[plan.location] ?? 'vietnam'}`)}</td><td><button type="button" onClick={() => onToggle(plan.name)} className={cn('relative h-5 w-9 rounded-full transition', plan.enabled ? 'bg-blue-600' : 'bg-slate-300')}><span className={cn('absolute top-1 size-3 rounded-full bg-white transition', plan.enabled ? 'left-5' : 'left-1')} /></button></td><td><button type="button" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><MoreHorizontal className="size-4" /></button></td></tr>)}</tbody></table></div><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>{t('vps.table.showing', { count: plans.length })}</span><div className="flex gap-1"><button className="rounded border px-2 py-1">‹</button><button className="rounded bg-blue-600 px-2.5 py-1 text-white">1</button><button className="rounded border px-2 py-1">2</button><button className="rounded border px-2 py-1">3</button><button className="rounded border px-2 py-1">…</button><button className="rounded border px-2 py-1">›</button></div></div></>
}
