/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as DashboardAdminRouteImport } from './routes/_dashboard/admin'
import { Route as DashboardCustomerRouteImport } from './routes/_dashboard/customer'
import { Route as authVerifyEmailConfirmRouteImport } from './routes/(auth)/verify-email.confirm'
import { Route as DashboardAdminDashboardIndexRouteImport } from './routes/_dashboard/admin/dashboard/index'
import { Route as DashboardAdminDashboardForbiddenRouteImport } from './routes/_dashboard/admin/dashboard/forbidden'
import { Route as DashboardCustomerDashboardIndexRouteImport } from './routes/_dashboard/customer/dashboard/index'
import { Route as DashboardAdminDashboardAuditLogsIndexRouteImport } from './routes/_dashboard/admin/dashboard/audit-logs/index'
import { Route as DashboardAdminDashboardMediaIndexRouteImport } from './routes/_dashboard/admin/dashboard/media/index'
import { Route as DashboardAdminDashboardOrdersIndexRouteImport } from './routes/_dashboard/admin/dashboard/orders/index'
import { Route as DashboardAdminDashboardPostsIndexRouteImport } from './routes/_dashboard/admin/dashboard/posts/index'
import { Route as DashboardAdminDashboardSettingsIndexRouteImport } from './routes/_dashboard/admin/dashboard/settings/index'
import { Route as DashboardAdminDashboardUsersIndexRouteImport } from './routes/_dashboard/admin/dashboard/users/index'
import { Route as DashboardCustomerDashboardBuyIndexRouteImport } from './routes/_dashboard/customer/dashboard/buy/index'
import { Route as DashboardCustomerDashboardCartIndexRouteImport } from './routes/_dashboard/customer/dashboard/cart/index'
import { Route as DashboardCustomerDashboardCheckoutIndexRouteImport } from './routes/_dashboard/customer/dashboard/checkout/index'
import { Route as DashboardCustomerDashboardOrdersIndexRouteImport } from './routes/_dashboard/customer/dashboard/orders/index'
import { Route as DashboardCustomerDashboardOrdersIdRouteImport } from './routes/_dashboard/customer/dashboard/orders/$id'
import { Route as DashboardCustomerDashboardServicesIndexRouteImport } from './routes/_dashboard/customer/dashboard/services/index'
import { Route as DashboardCustomerDashboardServicesIdRouteImport } from './routes/_dashboard/customer/dashboard/services/$id'
import { Route as DashboardAdminDashboardAppearanceMenuIndexRouteImport } from './routes/_dashboard/admin/dashboard/appearance/menu/index'
import { Route as DashboardAdminDashboardCatalogHostingIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/hosting/index'
import { Route as DashboardAdminDashboardCatalogPhysicalIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/physical/index'
import { Route as DashboardAdminDashboardCatalogProvidersIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/providers/index'
import { Route as DashboardAdminDashboardCatalogProxyIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/proxy/index'
import { Route as DashboardAdminDashboardCatalogProxyNewRouteImport } from './routes/_dashboard/admin/dashboard/catalog/proxy/new'
import { Route as DashboardAdminDashboardCatalogViaIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/via/index'
import { Route as DashboardAdminDashboardCatalogViaNewRouteImport } from './routes/_dashboard/admin/dashboard/catalog/via/new'
import { Route as DashboardAdminDashboardCatalogVpsIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/vps/index'
import { Route as DashboardAdminDashboardOrdersIdIndexRouteImport } from './routes/_dashboard/admin/dashboard/orders/$id/index'
import { Route as DashboardAdminDashboardPostsCategoriesIndexRouteImport } from './routes/_dashboard/admin/dashboard/posts/categories/index'
import { Route as DashboardAdminDashboardPostsNewIndexRouteImport } from './routes/_dashboard/admin/dashboard/posts/new/index'
import { Route as DashboardAdminDashboardPostsPlatformsIndexRouteImport } from './routes/_dashboard/admin/dashboard/posts/platforms/index'
import { Route as DashboardAdminDashboardUsersUserIdIndexRouteImport } from './routes/_dashboard/admin/dashboard/users/$userId/index'
import { Route as DashboardAdminDashboardUsersRolesIndexRouteImport } from './routes/_dashboard/admin/dashboard/users/roles/index'
import { Route as DashboardAdminDashboardCatalogHostingIdIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/hosting/$id/index'
import { Route as DashboardAdminDashboardCatalogHostingNewIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/hosting/new/index'
import { Route as DashboardAdminDashboardCatalogPhysicalIdIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/physical/$id/index'
import { Route as DashboardAdminDashboardCatalogPhysicalNewIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/physical/new/index'
import { Route as DashboardAdminDashboardCatalogProxyIdIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/proxy/$id/index'
import { Route as DashboardAdminDashboardCatalogViaIdIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/via/$id/index'
import { Route as DashboardAdminDashboardCatalogVpsIdIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/vps/$id/index'
import { Route as DashboardAdminDashboardCatalogVpsNewIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/vps/new/index'
import { Route as DashboardAdminDashboardPostsPostIdEditIndexRouteImport } from './routes/_dashboard/admin/dashboard/posts/$postId/edit/index'
import { Route as DashboardAdminDashboardCatalogHostingIdEditIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/hosting/$id/edit/index'
import { Route as DashboardAdminDashboardCatalogPhysicalIdEditIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/physical/$id/edit/index'
import { Route as DashboardAdminDashboardCatalogProxyIdEditIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/proxy/$id/edit/index'
import { Route as DashboardAdminDashboardCatalogViaIdEditIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/via/$id/edit/index'
import { Route as DashboardAdminDashboardCatalogVpsIdEditIndexRouteImport } from './routes/_dashboard/admin/dashboard/catalog/vps/$id/edit/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomerRoute = DashboardCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => DashboardRoute,
} as any)
const authVerifyEmailConfirmRoute = authVerifyEmailConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => authVerifyEmailRoute,
} as any)
const DashboardAdminDashboardIndexRoute =
  DashboardAdminDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardForbiddenRoute =
  DashboardAdminDashboardForbiddenRouteImport.update({
    id: '/dashboard/forbidden',
    path: '/dashboard/forbidden',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardCustomerDashboardIndexRoute =
  DashboardCustomerDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => DashboardCustomerRoute,
  } as any)
const DashboardAdminDashboardAuditLogsIndexRoute =
  DashboardAdminDashboardAuditLogsIndexRouteImport.update({
    id: '/dashboard/audit-logs/',
    path: '/dashboard/audit-logs/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardMediaIndexRoute =
  DashboardAdminDashboardMediaIndexRouteImport.update({
    id: '/dashboard/media/',
    path: '/dashboard/media/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardOrdersIndexRoute =
  DashboardAdminDashboardOrdersIndexRouteImport.update({
    id: '/dashboard/orders/',
    path: '/dashboard/orders/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardPostsIndexRoute =
  DashboardAdminDashboardPostsIndexRouteImport.update({
    id: '/dashboard/posts/',
    path: '/dashboard/posts/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardSettingsIndexRoute =
  DashboardAdminDashboardSettingsIndexRouteImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardUsersIndexRoute =
  DashboardAdminDashboardUsersIndexRouteImport.update({
    id: '/dashboard/users/',
    path: '/dashboard/users/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardCustomerDashboardBuyIndexRoute =
  DashboardCustomerDashboardBuyIndexRouteImport.update({
    id: '/dashboard/buy/',
    path: '/dashboard/buy/',
    getParentRoute: () => DashboardCustomerRoute,
  } as any)
const DashboardCustomerDashboardCartIndexRoute =
  DashboardCustomerDashboardCartIndexRouteImport.update({
    id: '/dashboard/cart/',
    path: '/dashboard/cart/',
    getParentRoute: () => DashboardCustomerRoute,
  } as any)
const DashboardCustomerDashboardCheckoutIndexRoute =
  DashboardCustomerDashboardCheckoutIndexRouteImport.update({
    id: '/dashboard/checkout/',
    path: '/dashboard/checkout/',
    getParentRoute: () => DashboardCustomerRoute,
  } as any)
const DashboardCustomerDashboardOrdersIndexRoute =
  DashboardCustomerDashboardOrdersIndexRouteImport.update({
    id: '/dashboard/orders/',
    path: '/dashboard/orders/',
    getParentRoute: () => DashboardCustomerRoute,
  } as any)
const DashboardCustomerDashboardOrdersIdRoute =
  DashboardCustomerDashboardOrdersIdRouteImport.update({
    id: '/dashboard/orders/$id',
    path: '/dashboard/orders/$id',
    getParentRoute: () => DashboardCustomerRoute,
  } as any)
const DashboardCustomerDashboardServicesIndexRoute =
  DashboardCustomerDashboardServicesIndexRouteImport.update({
    id: '/dashboard/services/',
    path: '/dashboard/services/',
    getParentRoute: () => DashboardCustomerRoute,
  } as any)
const DashboardCustomerDashboardServicesIdRoute =
  DashboardCustomerDashboardServicesIdRouteImport.update({
    id: '/dashboard/services/$id',
    path: '/dashboard/services/$id',
    getParentRoute: () => DashboardCustomerRoute,
  } as any)
const DashboardAdminDashboardAppearanceMenuIndexRoute =
  DashboardAdminDashboardAppearanceMenuIndexRouteImport.update({
    id: '/dashboard/appearance/menu/',
    path: '/dashboard/appearance/menu/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogHostingIndexRoute =
  DashboardAdminDashboardCatalogHostingIndexRouteImport.update({
    id: '/dashboard/catalog/hosting/',
    path: '/dashboard/catalog/hosting/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogPhysicalIndexRoute =
  DashboardAdminDashboardCatalogPhysicalIndexRouteImport.update({
    id: '/dashboard/catalog/physical/',
    path: '/dashboard/catalog/physical/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogProvidersIndexRoute =
  DashboardAdminDashboardCatalogProvidersIndexRouteImport.update({
    id: '/dashboard/catalog/providers/',
    path: '/dashboard/catalog/providers/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogProxyIndexRoute =
  DashboardAdminDashboardCatalogProxyIndexRouteImport.update({
    id: '/dashboard/catalog/proxy/',
    path: '/dashboard/catalog/proxy/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogProxyNewRoute =
  DashboardAdminDashboardCatalogProxyNewRouteImport.update({
    id: '/dashboard/catalog/proxy/new',
    path: '/dashboard/catalog/proxy/new',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogViaIndexRoute =
  DashboardAdminDashboardCatalogViaIndexRouteImport.update({
    id: '/dashboard/catalog/via/',
    path: '/dashboard/catalog/via/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogViaNewRoute =
  DashboardAdminDashboardCatalogViaNewRouteImport.update({
    id: '/dashboard/catalog/via/new',
    path: '/dashboard/catalog/via/new',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogVpsIndexRoute =
  DashboardAdminDashboardCatalogVpsIndexRouteImport.update({
    id: '/dashboard/catalog/vps/',
    path: '/dashboard/catalog/vps/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardOrdersIdIndexRoute =
  DashboardAdminDashboardOrdersIdIndexRouteImport.update({
    id: '/dashboard/orders/$id/',
    path: '/dashboard/orders/$id/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardPostsCategoriesIndexRoute =
  DashboardAdminDashboardPostsCategoriesIndexRouteImport.update({
    id: '/dashboard/posts/categories/',
    path: '/dashboard/posts/categories/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardPostsNewIndexRoute =
  DashboardAdminDashboardPostsNewIndexRouteImport.update({
    id: '/dashboard/posts/new/',
    path: '/dashboard/posts/new/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardPostsPlatformsIndexRoute =
  DashboardAdminDashboardPostsPlatformsIndexRouteImport.update({
    id: '/dashboard/posts/platforms/',
    path: '/dashboard/posts/platforms/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardUsersUserIdIndexRoute =
  DashboardAdminDashboardUsersUserIdIndexRouteImport.update({
    id: '/dashboard/users/$userId/',
    path: '/dashboard/users/$userId/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardUsersRolesIndexRoute =
  DashboardAdminDashboardUsersRolesIndexRouteImport.update({
    id: '/dashboard/users/roles/',
    path: '/dashboard/users/roles/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogHostingIdIndexRoute =
  DashboardAdminDashboardCatalogHostingIdIndexRouteImport.update({
    id: '/dashboard/catalog/hosting/$id/',
    path: '/dashboard/catalog/hosting/$id/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogHostingNewIndexRoute =
  DashboardAdminDashboardCatalogHostingNewIndexRouteImport.update({
    id: '/dashboard/catalog/hosting/new/',
    path: '/dashboard/catalog/hosting/new/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogPhysicalIdIndexRoute =
  DashboardAdminDashboardCatalogPhysicalIdIndexRouteImport.update({
    id: '/dashboard/catalog/physical/$id/',
    path: '/dashboard/catalog/physical/$id/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogPhysicalNewIndexRoute =
  DashboardAdminDashboardCatalogPhysicalNewIndexRouteImport.update({
    id: '/dashboard/catalog/physical/new/',
    path: '/dashboard/catalog/physical/new/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogProxyIdIndexRoute =
  DashboardAdminDashboardCatalogProxyIdIndexRouteImport.update({
    id: '/dashboard/catalog/proxy/$id/',
    path: '/dashboard/catalog/proxy/$id/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogViaIdIndexRoute =
  DashboardAdminDashboardCatalogViaIdIndexRouteImport.update({
    id: '/dashboard/catalog/via/$id/',
    path: '/dashboard/catalog/via/$id/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogVpsIdIndexRoute =
  DashboardAdminDashboardCatalogVpsIdIndexRouteImport.update({
    id: '/dashboard/catalog/vps/$id/',
    path: '/dashboard/catalog/vps/$id/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogVpsNewIndexRoute =
  DashboardAdminDashboardCatalogVpsNewIndexRouteImport.update({
    id: '/dashboard/catalog/vps/new/',
    path: '/dashboard/catalog/vps/new/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardPostsPostIdEditIndexRoute =
  DashboardAdminDashboardPostsPostIdEditIndexRouteImport.update({
    id: '/dashboard/posts/$postId/edit/',
    path: '/dashboard/posts/$postId/edit/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogHostingIdEditIndexRoute =
  DashboardAdminDashboardCatalogHostingIdEditIndexRouteImport.update({
    id: '/dashboard/catalog/hosting/$id/edit/',
    path: '/dashboard/catalog/hosting/$id/edit/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogPhysicalIdEditIndexRoute =
  DashboardAdminDashboardCatalogPhysicalIdEditIndexRouteImport.update({
    id: '/dashboard/catalog/physical/$id/edit/',
    path: '/dashboard/catalog/physical/$id/edit/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogProxyIdEditIndexRoute =
  DashboardAdminDashboardCatalogProxyIdEditIndexRouteImport.update({
    id: '/dashboard/catalog/proxy/$id/edit/',
    path: '/dashboard/catalog/proxy/$id/edit/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogViaIdEditIndexRoute =
  DashboardAdminDashboardCatalogViaIdEditIndexRouteImport.update({
    id: '/dashboard/catalog/via/$id/edit/',
    path: '/dashboard/catalog/via/$id/edit/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDashboardCatalogVpsIdEditIndexRoute =
  DashboardAdminDashboardCatalogVpsIdEditIndexRouteImport.update({
    id: '/dashboard/catalog/vps/$id/edit/',
    path: '/dashboard/catalog/vps/$id/edit/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRouteWithChildren
  '/admin': typeof DashboardAdminRouteWithChildren
  '/customer': typeof DashboardCustomerRouteWithChildren
  '/verify-email/confirm': typeof authVerifyEmailConfirmRoute
  '/admin/dashboard/forbidden': typeof DashboardAdminDashboardForbiddenRoute
  '/admin/dashboard/': typeof DashboardAdminDashboardIndexRoute
  '/customer/dashboard/': typeof DashboardCustomerDashboardIndexRoute
  '/customer/dashboard/orders/$id': typeof DashboardCustomerDashboardOrdersIdRoute
  '/customer/dashboard/services/$id': typeof DashboardCustomerDashboardServicesIdRoute
  '/admin/dashboard/audit-logs/': typeof DashboardAdminDashboardAuditLogsIndexRoute
  '/admin/dashboard/media/': typeof DashboardAdminDashboardMediaIndexRoute
  '/admin/dashboard/orders/': typeof DashboardAdminDashboardOrdersIndexRoute
  '/admin/dashboard/posts/': typeof DashboardAdminDashboardPostsIndexRoute
  '/admin/dashboard/settings/': typeof DashboardAdminDashboardSettingsIndexRoute
  '/admin/dashboard/users/': typeof DashboardAdminDashboardUsersIndexRoute
  '/customer/dashboard/buy/': typeof DashboardCustomerDashboardBuyIndexRoute
  '/customer/dashboard/cart/': typeof DashboardCustomerDashboardCartIndexRoute
  '/customer/dashboard/checkout/': typeof DashboardCustomerDashboardCheckoutIndexRoute
  '/customer/dashboard/orders/': typeof DashboardCustomerDashboardOrdersIndexRoute
  '/customer/dashboard/services/': typeof DashboardCustomerDashboardServicesIndexRoute
  '/admin/dashboard/catalog/proxy/new': typeof DashboardAdminDashboardCatalogProxyNewRoute
  '/admin/dashboard/catalog/via/new': typeof DashboardAdminDashboardCatalogViaNewRoute
  '/admin/dashboard/appearance/menu/': typeof DashboardAdminDashboardAppearanceMenuIndexRoute
  '/admin/dashboard/catalog/hosting/': typeof DashboardAdminDashboardCatalogHostingIndexRoute
  '/admin/dashboard/catalog/physical/': typeof DashboardAdminDashboardCatalogPhysicalIndexRoute
  '/admin/dashboard/catalog/providers/': typeof DashboardAdminDashboardCatalogProvidersIndexRoute
  '/admin/dashboard/catalog/proxy/': typeof DashboardAdminDashboardCatalogProxyIndexRoute
  '/admin/dashboard/catalog/via/': typeof DashboardAdminDashboardCatalogViaIndexRoute
  '/admin/dashboard/catalog/vps/': typeof DashboardAdminDashboardCatalogVpsIndexRoute
  '/admin/dashboard/orders/$id/': typeof DashboardAdminDashboardOrdersIdIndexRoute
  '/admin/dashboard/posts/categories/': typeof DashboardAdminDashboardPostsCategoriesIndexRoute
  '/admin/dashboard/posts/new/': typeof DashboardAdminDashboardPostsNewIndexRoute
  '/admin/dashboard/posts/platforms/': typeof DashboardAdminDashboardPostsPlatformsIndexRoute
  '/admin/dashboard/users/$userId/': typeof DashboardAdminDashboardUsersUserIdIndexRoute
  '/admin/dashboard/users/roles/': typeof DashboardAdminDashboardUsersRolesIndexRoute
  '/admin/dashboard/catalog/hosting/$id/': typeof DashboardAdminDashboardCatalogHostingIdIndexRoute
  '/admin/dashboard/catalog/hosting/new/': typeof DashboardAdminDashboardCatalogHostingNewIndexRoute
  '/admin/dashboard/catalog/physical/$id/': typeof DashboardAdminDashboardCatalogPhysicalIdIndexRoute
  '/admin/dashboard/catalog/physical/new/': typeof DashboardAdminDashboardCatalogPhysicalNewIndexRoute
  '/admin/dashboard/catalog/proxy/$id/': typeof DashboardAdminDashboardCatalogProxyIdIndexRoute
  '/admin/dashboard/catalog/via/$id/': typeof DashboardAdminDashboardCatalogViaIdIndexRoute
  '/admin/dashboard/catalog/vps/$id/': typeof DashboardAdminDashboardCatalogVpsIdIndexRoute
  '/admin/dashboard/catalog/vps/new/': typeof DashboardAdminDashboardCatalogVpsNewIndexRoute
  '/admin/dashboard/posts/$postId/edit/': typeof DashboardAdminDashboardPostsPostIdEditIndexRoute
  '/admin/dashboard/catalog/hosting/$id/edit/': typeof DashboardAdminDashboardCatalogHostingIdEditIndexRoute
  '/admin/dashboard/catalog/physical/$id/edit/': typeof DashboardAdminDashboardCatalogPhysicalIdEditIndexRoute
  '/admin/dashboard/catalog/proxy/$id/edit/': typeof DashboardAdminDashboardCatalogProxyIdEditIndexRoute
  '/admin/dashboard/catalog/via/$id/edit/': typeof DashboardAdminDashboardCatalogViaIdEditIndexRoute
  '/admin/dashboard/catalog/vps/$id/edit/': typeof DashboardAdminDashboardCatalogVpsIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRouteWithChildren
  '/admin': typeof DashboardAdminRouteWithChildren
  '/customer': typeof DashboardCustomerRouteWithChildren
  '/verify-email/confirm': typeof authVerifyEmailConfirmRoute
  '/admin/dashboard/forbidden': typeof DashboardAdminDashboardForbiddenRoute
  '/admin/dashboard': typeof DashboardAdminDashboardIndexRoute
  '/customer/dashboard': typeof DashboardCustomerDashboardIndexRoute
  '/customer/dashboard/orders/$id': typeof DashboardCustomerDashboardOrdersIdRoute
  '/customer/dashboard/services/$id': typeof DashboardCustomerDashboardServicesIdRoute
  '/admin/dashboard/audit-logs': typeof DashboardAdminDashboardAuditLogsIndexRoute
  '/admin/dashboard/media': typeof DashboardAdminDashboardMediaIndexRoute
  '/admin/dashboard/orders': typeof DashboardAdminDashboardOrdersIndexRoute
  '/admin/dashboard/posts': typeof DashboardAdminDashboardPostsIndexRoute
  '/admin/dashboard/settings': typeof DashboardAdminDashboardSettingsIndexRoute
  '/admin/dashboard/users': typeof DashboardAdminDashboardUsersIndexRoute
  '/customer/dashboard/buy': typeof DashboardCustomerDashboardBuyIndexRoute
  '/customer/dashboard/cart': typeof DashboardCustomerDashboardCartIndexRoute
  '/customer/dashboard/checkout': typeof DashboardCustomerDashboardCheckoutIndexRoute
  '/customer/dashboard/orders': typeof DashboardCustomerDashboardOrdersIndexRoute
  '/customer/dashboard/services': typeof DashboardCustomerDashboardServicesIndexRoute
  '/admin/dashboard/catalog/proxy/new': typeof DashboardAdminDashboardCatalogProxyNewRoute
  '/admin/dashboard/catalog/via/new': typeof DashboardAdminDashboardCatalogViaNewRoute
  '/admin/dashboard/appearance/menu': typeof DashboardAdminDashboardAppearanceMenuIndexRoute
  '/admin/dashboard/catalog/hosting': typeof DashboardAdminDashboardCatalogHostingIndexRoute
  '/admin/dashboard/catalog/physical': typeof DashboardAdminDashboardCatalogPhysicalIndexRoute
  '/admin/dashboard/catalog/providers': typeof DashboardAdminDashboardCatalogProvidersIndexRoute
  '/admin/dashboard/catalog/proxy': typeof DashboardAdminDashboardCatalogProxyIndexRoute
  '/admin/dashboard/catalog/via': typeof DashboardAdminDashboardCatalogViaIndexRoute
  '/admin/dashboard/catalog/vps': typeof DashboardAdminDashboardCatalogVpsIndexRoute
  '/admin/dashboard/orders/$id': typeof DashboardAdminDashboardOrdersIdIndexRoute
  '/admin/dashboard/posts/categories': typeof DashboardAdminDashboardPostsCategoriesIndexRoute
  '/admin/dashboard/posts/new': typeof DashboardAdminDashboardPostsNewIndexRoute
  '/admin/dashboard/posts/platforms': typeof DashboardAdminDashboardPostsPlatformsIndexRoute
  '/admin/dashboard/users/$userId': typeof DashboardAdminDashboardUsersUserIdIndexRoute
  '/admin/dashboard/users/roles': typeof DashboardAdminDashboardUsersRolesIndexRoute
  '/admin/dashboard/catalog/hosting/$id': typeof DashboardAdminDashboardCatalogHostingIdIndexRoute
  '/admin/dashboard/catalog/hosting/new': typeof DashboardAdminDashboardCatalogHostingNewIndexRoute
  '/admin/dashboard/catalog/physical/$id': typeof DashboardAdminDashboardCatalogPhysicalIdIndexRoute
  '/admin/dashboard/catalog/physical/new': typeof DashboardAdminDashboardCatalogPhysicalNewIndexRoute
  '/admin/dashboard/catalog/proxy/$id': typeof DashboardAdminDashboardCatalogProxyIdIndexRoute
  '/admin/dashboard/catalog/via/$id': typeof DashboardAdminDashboardCatalogViaIdIndexRoute
  '/admin/dashboard/catalog/vps/$id': typeof DashboardAdminDashboardCatalogVpsIdIndexRoute
  '/admin/dashboard/catalog/vps/new': typeof DashboardAdminDashboardCatalogVpsNewIndexRoute
  '/admin/dashboard/posts/$postId/edit': typeof DashboardAdminDashboardPostsPostIdEditIndexRoute
  '/admin/dashboard/catalog/hosting/$id/edit': typeof DashboardAdminDashboardCatalogHostingIdEditIndexRoute
  '/admin/dashboard/catalog/physical/$id/edit': typeof DashboardAdminDashboardCatalogPhysicalIdEditIndexRoute
  '/admin/dashboard/catalog/proxy/$id/edit': typeof DashboardAdminDashboardCatalogProxyIdEditIndexRoute
  '/admin/dashboard/catalog/via/$id/edit': typeof DashboardAdminDashboardCatalogViaIdEditIndexRoute
  '/admin/dashboard/catalog/vps/$id/edit': typeof DashboardAdminDashboardCatalogVpsIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRouteWithChildren
  '/_dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/_dashboard/customer': typeof DashboardCustomerRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(auth)/verify-email/confirm': typeof authVerifyEmailConfirmRoute
  '/_dashboard/admin/dashboard/forbidden': typeof DashboardAdminDashboardForbiddenRoute
  '/_dashboard/admin/dashboard/': typeof DashboardAdminDashboardIndexRoute
  '/_dashboard/customer/dashboard/': typeof DashboardCustomerDashboardIndexRoute
  '/_dashboard/customer/dashboard/orders/$id': typeof DashboardCustomerDashboardOrdersIdRoute
  '/_dashboard/customer/dashboard/services/$id': typeof DashboardCustomerDashboardServicesIdRoute
  '/_dashboard/admin/dashboard/audit-logs/': typeof DashboardAdminDashboardAuditLogsIndexRoute
  '/_dashboard/admin/dashboard/media/': typeof DashboardAdminDashboardMediaIndexRoute
  '/_dashboard/admin/dashboard/orders/': typeof DashboardAdminDashboardOrdersIndexRoute
  '/_dashboard/admin/dashboard/posts/': typeof DashboardAdminDashboardPostsIndexRoute
  '/_dashboard/admin/dashboard/settings/': typeof DashboardAdminDashboardSettingsIndexRoute
  '/_dashboard/admin/dashboard/users/': typeof DashboardAdminDashboardUsersIndexRoute
  '/_dashboard/customer/dashboard/buy/': typeof DashboardCustomerDashboardBuyIndexRoute
  '/_dashboard/customer/dashboard/cart/': typeof DashboardCustomerDashboardCartIndexRoute
  '/_dashboard/customer/dashboard/checkout/': typeof DashboardCustomerDashboardCheckoutIndexRoute
  '/_dashboard/customer/dashboard/orders/': typeof DashboardCustomerDashboardOrdersIndexRoute
  '/_dashboard/customer/dashboard/services/': typeof DashboardCustomerDashboardServicesIndexRoute
  '/_dashboard/admin/dashboard/catalog/proxy/new': typeof DashboardAdminDashboardCatalogProxyNewRoute
  '/_dashboard/admin/dashboard/catalog/via/new': typeof DashboardAdminDashboardCatalogViaNewRoute
  '/_dashboard/admin/dashboard/appearance/menu/': typeof DashboardAdminDashboardAppearanceMenuIndexRoute
  '/_dashboard/admin/dashboard/catalog/hosting/': typeof DashboardAdminDashboardCatalogHostingIndexRoute
  '/_dashboard/admin/dashboard/catalog/physical/': typeof DashboardAdminDashboardCatalogPhysicalIndexRoute
  '/_dashboard/admin/dashboard/catalog/providers/': typeof DashboardAdminDashboardCatalogProvidersIndexRoute
  '/_dashboard/admin/dashboard/catalog/proxy/': typeof DashboardAdminDashboardCatalogProxyIndexRoute
  '/_dashboard/admin/dashboard/catalog/via/': typeof DashboardAdminDashboardCatalogViaIndexRoute
  '/_dashboard/admin/dashboard/catalog/vps/': typeof DashboardAdminDashboardCatalogVpsIndexRoute
  '/_dashboard/admin/dashboard/orders/$id/': typeof DashboardAdminDashboardOrdersIdIndexRoute
  '/_dashboard/admin/dashboard/posts/categories/': typeof DashboardAdminDashboardPostsCategoriesIndexRoute
  '/_dashboard/admin/dashboard/posts/new/': typeof DashboardAdminDashboardPostsNewIndexRoute
  '/_dashboard/admin/dashboard/posts/platforms/': typeof DashboardAdminDashboardPostsPlatformsIndexRoute
  '/_dashboard/admin/dashboard/users/$userId/': typeof DashboardAdminDashboardUsersUserIdIndexRoute
  '/_dashboard/admin/dashboard/users/roles/': typeof DashboardAdminDashboardUsersRolesIndexRoute
  '/_dashboard/admin/dashboard/catalog/hosting/$id/': typeof DashboardAdminDashboardCatalogHostingIdIndexRoute
  '/_dashboard/admin/dashboard/catalog/hosting/new/': typeof DashboardAdminDashboardCatalogHostingNewIndexRoute
  '/_dashboard/admin/dashboard/catalog/physical/$id/': typeof DashboardAdminDashboardCatalogPhysicalIdIndexRoute
  '/_dashboard/admin/dashboard/catalog/physical/new/': typeof DashboardAdminDashboardCatalogPhysicalNewIndexRoute
  '/_dashboard/admin/dashboard/catalog/proxy/$id/': typeof DashboardAdminDashboardCatalogProxyIdIndexRoute
  '/_dashboard/admin/dashboard/catalog/via/$id/': typeof DashboardAdminDashboardCatalogViaIdIndexRoute
  '/_dashboard/admin/dashboard/catalog/vps/$id/': typeof DashboardAdminDashboardCatalogVpsIdIndexRoute
  '/_dashboard/admin/dashboard/catalog/vps/new/': typeof DashboardAdminDashboardCatalogVpsNewIndexRoute
  '/_dashboard/admin/dashboard/posts/$postId/edit/': typeof DashboardAdminDashboardPostsPostIdEditIndexRoute
  '/_dashboard/admin/dashboard/catalog/hosting/$id/edit/': typeof DashboardAdminDashboardCatalogHostingIdEditIndexRoute
  '/_dashboard/admin/dashboard/catalog/physical/$id/edit/': typeof DashboardAdminDashboardCatalogPhysicalIdEditIndexRoute
  '/_dashboard/admin/dashboard/catalog/proxy/$id/edit/': typeof DashboardAdminDashboardCatalogProxyIdEditIndexRoute
  '/_dashboard/admin/dashboard/catalog/via/$id/edit/': typeof DashboardAdminDashboardCatalogViaIdEditIndexRoute
  '/_dashboard/admin/dashboard/catalog/vps/$id/edit/': typeof DashboardAdminDashboardCatalogVpsIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin'
    | '/customer'
    | '/verify-email/confirm'
    | '/admin/dashboard/forbidden'
    | '/admin/dashboard/'
    | '/customer/dashboard/'
    | '/customer/dashboard/orders/$id'
    | '/customer/dashboard/services/$id'
    | '/admin/dashboard/audit-logs/'
    | '/admin/dashboard/media/'
    | '/admin/dashboard/orders/'
    | '/admin/dashboard/posts/'
    | '/admin/dashboard/settings/'
    | '/admin/dashboard/users/'
    | '/customer/dashboard/buy/'
    | '/customer/dashboard/cart/'
    | '/customer/dashboard/checkout/'
    | '/customer/dashboard/orders/'
    | '/customer/dashboard/services/'
    | '/admin/dashboard/catalog/proxy/new'
    | '/admin/dashboard/catalog/via/new'
    | '/admin/dashboard/appearance/menu/'
    | '/admin/dashboard/catalog/hosting/'
    | '/admin/dashboard/catalog/physical/'
    | '/admin/dashboard/catalog/providers/'
    | '/admin/dashboard/catalog/proxy/'
    | '/admin/dashboard/catalog/via/'
    | '/admin/dashboard/catalog/vps/'
    | '/admin/dashboard/orders/$id/'
    | '/admin/dashboard/posts/categories/'
    | '/admin/dashboard/posts/new/'
    | '/admin/dashboard/posts/platforms/'
    | '/admin/dashboard/users/$userId/'
    | '/admin/dashboard/users/roles/'
    | '/admin/dashboard/catalog/hosting/$id/'
    | '/admin/dashboard/catalog/hosting/new/'
    | '/admin/dashboard/catalog/physical/$id/'
    | '/admin/dashboard/catalog/physical/new/'
    | '/admin/dashboard/catalog/proxy/$id/'
    | '/admin/dashboard/catalog/via/$id/'
    | '/admin/dashboard/catalog/vps/$id/'
    | '/admin/dashboard/catalog/vps/new/'
    | '/admin/dashboard/posts/$postId/edit/'
    | '/admin/dashboard/catalog/hosting/$id/edit/'
    | '/admin/dashboard/catalog/physical/$id/edit/'
    | '/admin/dashboard/catalog/proxy/$id/edit/'
    | '/admin/dashboard/catalog/via/$id/edit/'
    | '/admin/dashboard/catalog/vps/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin'
    | '/customer'
    | '/verify-email/confirm'
    | '/admin/dashboard/forbidden'
    | '/admin/dashboard'
    | '/customer/dashboard'
    | '/customer/dashboard/orders/$id'
    | '/customer/dashboard/services/$id'
    | '/admin/dashboard/audit-logs'
    | '/admin/dashboard/media'
    | '/admin/dashboard/orders'
    | '/admin/dashboard/posts'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/users'
    | '/customer/dashboard/buy'
    | '/customer/dashboard/cart'
    | '/customer/dashboard/checkout'
    | '/customer/dashboard/orders'
    | '/customer/dashboard/services'
    | '/admin/dashboard/catalog/proxy/new'
    | '/admin/dashboard/catalog/via/new'
    | '/admin/dashboard/appearance/menu'
    | '/admin/dashboard/catalog/hosting'
    | '/admin/dashboard/catalog/physical'
    | '/admin/dashboard/catalog/providers'
    | '/admin/dashboard/catalog/proxy'
    | '/admin/dashboard/catalog/via'
    | '/admin/dashboard/catalog/vps'
    | '/admin/dashboard/orders/$id'
    | '/admin/dashboard/posts/categories'
    | '/admin/dashboard/posts/new'
    | '/admin/dashboard/posts/platforms'
    | '/admin/dashboard/users/$userId'
    | '/admin/dashboard/users/roles'
    | '/admin/dashboard/catalog/hosting/$id'
    | '/admin/dashboard/catalog/hosting/new'
    | '/admin/dashboard/catalog/physical/$id'
    | '/admin/dashboard/catalog/physical/new'
    | '/admin/dashboard/catalog/proxy/$id'
    | '/admin/dashboard/catalog/via/$id'
    | '/admin/dashboard/catalog/vps/$id'
    | '/admin/dashboard/catalog/vps/new'
    | '/admin/dashboard/posts/$postId/edit'
    | '/admin/dashboard/catalog/hosting/$id/edit'
    | '/admin/dashboard/catalog/physical/$id/edit'
    | '/admin/dashboard/catalog/proxy/$id/edit'
    | '/admin/dashboard/catalog/via/$id/edit'
    | '/admin/dashboard/catalog/vps/$id/edit'
  id:
    | '__root__'
    | '/_dashboard'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/_dashboard/admin'
    | '/_dashboard/customer'
    | '/(public)/'
    | '/(auth)/verify-email/confirm'
    | '/_dashboard/admin/dashboard/forbidden'
    | '/_dashboard/admin/dashboard/'
    | '/_dashboard/customer/dashboard/'
    | '/_dashboard/customer/dashboard/orders/$id'
    | '/_dashboard/customer/dashboard/services/$id'
    | '/_dashboard/admin/dashboard/audit-logs/'
    | '/_dashboard/admin/dashboard/media/'
    | '/_dashboard/admin/dashboard/orders/'
    | '/_dashboard/admin/dashboard/posts/'
    | '/_dashboard/admin/dashboard/settings/'
    | '/_dashboard/admin/dashboard/users/'
    | '/_dashboard/customer/dashboard/buy/'
    | '/_dashboard/customer/dashboard/cart/'
    | '/_dashboard/customer/dashboard/checkout/'
    | '/_dashboard/customer/dashboard/orders/'
    | '/_dashboard/customer/dashboard/services/'
    | '/_dashboard/admin/dashboard/catalog/proxy/new'
    | '/_dashboard/admin/dashboard/catalog/via/new'
    | '/_dashboard/admin/dashboard/appearance/menu/'
    | '/_dashboard/admin/dashboard/catalog/hosting/'
    | '/_dashboard/admin/dashboard/catalog/physical/'
    | '/_dashboard/admin/dashboard/catalog/providers/'
    | '/_dashboard/admin/dashboard/catalog/proxy/'
    | '/_dashboard/admin/dashboard/catalog/via/'
    | '/_dashboard/admin/dashboard/catalog/vps/'
    | '/_dashboard/admin/dashboard/orders/$id/'
    | '/_dashboard/admin/dashboard/posts/categories/'
    | '/_dashboard/admin/dashboard/posts/new/'
    | '/_dashboard/admin/dashboard/posts/platforms/'
    | '/_dashboard/admin/dashboard/users/$userId/'
    | '/_dashboard/admin/dashboard/users/roles/'
    | '/_dashboard/admin/dashboard/catalog/hosting/$id/'
    | '/_dashboard/admin/dashboard/catalog/hosting/new/'
    | '/_dashboard/admin/dashboard/catalog/physical/$id/'
    | '/_dashboard/admin/dashboard/catalog/physical/new/'
    | '/_dashboard/admin/dashboard/catalog/proxy/$id/'
    | '/_dashboard/admin/dashboard/catalog/via/$id/'
    | '/_dashboard/admin/dashboard/catalog/vps/$id/'
    | '/_dashboard/admin/dashboard/catalog/vps/new/'
    | '/_dashboard/admin/dashboard/posts/$postId/edit/'
    | '/_dashboard/admin/dashboard/catalog/hosting/$id/edit/'
    | '/_dashboard/admin/dashboard/catalog/physical/$id/edit/'
    | '/_dashboard/admin/dashboard/catalog/proxy/$id/edit/'
    | '/_dashboard/admin/dashboard/catalog/via/$id/edit/'
    | '/_dashboard/admin/dashboard/catalog/vps/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/admin': {
      id: '/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/customer': {
      id: '/_dashboard/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof DashboardCustomerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(auth)/verify-email/confirm': {
      id: '/(auth)/verify-email/confirm'
      path: '/confirm'
      fullPath: '/verify-email/confirm'
      preLoaderRoute: typeof authVerifyEmailConfirmRouteImport
      parentRoute: typeof authVerifyEmailRoute
    }
    '/_dashboard/admin/dashboard/': {
      id: '/_dashboard/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof DashboardAdminDashboardIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/forbidden': {
      id: '/_dashboard/admin/dashboard/forbidden'
      path: '/dashboard/forbidden'
      fullPath: '/admin/dashboard/forbidden'
      preLoaderRoute: typeof DashboardAdminDashboardForbiddenRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/customer/dashboard/': {
      id: '/_dashboard/customer/dashboard/'
      path: '/dashboard'
      fullPath: '/customer/dashboard/'
      preLoaderRoute: typeof DashboardCustomerDashboardIndexRouteImport
      parentRoute: typeof DashboardCustomerRoute
    }
    '/_dashboard/admin/dashboard/audit-logs/': {
      id: '/_dashboard/admin/dashboard/audit-logs/'
      path: '/dashboard/audit-logs'
      fullPath: '/admin/dashboard/audit-logs/'
      preLoaderRoute: typeof DashboardAdminDashboardAuditLogsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/media/': {
      id: '/_dashboard/admin/dashboard/media/'
      path: '/dashboard/media'
      fullPath: '/admin/dashboard/media/'
      preLoaderRoute: typeof DashboardAdminDashboardMediaIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/orders/': {
      id: '/_dashboard/admin/dashboard/orders/'
      path: '/dashboard/orders'
      fullPath: '/admin/dashboard/orders/'
      preLoaderRoute: typeof DashboardAdminDashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/posts/': {
      id: '/_dashboard/admin/dashboard/posts/'
      path: '/dashboard/posts'
      fullPath: '/admin/dashboard/posts/'
      preLoaderRoute: typeof DashboardAdminDashboardPostsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/settings/': {
      id: '/_dashboard/admin/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/admin/dashboard/settings/'
      preLoaderRoute: typeof DashboardAdminDashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/users/': {
      id: '/_dashboard/admin/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/admin/dashboard/users/'
      preLoaderRoute: typeof DashboardAdminDashboardUsersIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/customer/dashboard/buy/': {
      id: '/_dashboard/customer/dashboard/buy/'
      path: '/dashboard/buy'
      fullPath: '/customer/dashboard/buy/'
      preLoaderRoute: typeof DashboardCustomerDashboardBuyIndexRouteImport
      parentRoute: typeof DashboardCustomerRoute
    }
    '/_dashboard/customer/dashboard/cart/': {
      id: '/_dashboard/customer/dashboard/cart/'
      path: '/dashboard/cart'
      fullPath: '/customer/dashboard/cart/'
      preLoaderRoute: typeof DashboardCustomerDashboardCartIndexRouteImport
      parentRoute: typeof DashboardCustomerRoute
    }
    '/_dashboard/customer/dashboard/checkout/': {
      id: '/_dashboard/customer/dashboard/checkout/'
      path: '/dashboard/checkout'
      fullPath: '/customer/dashboard/checkout/'
      preLoaderRoute: typeof DashboardCustomerDashboardCheckoutIndexRouteImport
      parentRoute: typeof DashboardCustomerRoute
    }
    '/_dashboard/customer/dashboard/orders/': {
      id: '/_dashboard/customer/dashboard/orders/'
      path: '/dashboard/orders'
      fullPath: '/customer/dashboard/orders/'
      preLoaderRoute: typeof DashboardCustomerDashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardCustomerRoute
    }
    '/_dashboard/customer/dashboard/orders/$id': {
      id: '/_dashboard/customer/dashboard/orders/$id'
      path: '/dashboard/orders/$id'
      fullPath: '/customer/dashboard/orders/$id'
      preLoaderRoute: typeof DashboardCustomerDashboardOrdersIdRouteImport
      parentRoute: typeof DashboardCustomerRoute
    }
    '/_dashboard/customer/dashboard/services/': {
      id: '/_dashboard/customer/dashboard/services/'
      path: '/dashboard/services'
      fullPath: '/customer/dashboard/services/'
      preLoaderRoute: typeof DashboardCustomerDashboardServicesIndexRouteImport
      parentRoute: typeof DashboardCustomerRoute
    }
    '/_dashboard/customer/dashboard/services/$id': {
      id: '/_dashboard/customer/dashboard/services/$id'
      path: '/dashboard/services/$id'
      fullPath: '/customer/dashboard/services/$id'
      preLoaderRoute: typeof DashboardCustomerDashboardServicesIdRouteImport
      parentRoute: typeof DashboardCustomerRoute
    }
    '/_dashboard/admin/dashboard/appearance/menu/': {
      id: '/_dashboard/admin/dashboard/appearance/menu/'
      path: '/dashboard/appearance/menu'
      fullPath: '/admin/dashboard/appearance/menu/'
      preLoaderRoute: typeof DashboardAdminDashboardAppearanceMenuIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/hosting/': {
      id: '/_dashboard/admin/dashboard/catalog/hosting/'
      path: '/dashboard/catalog/hosting'
      fullPath: '/admin/dashboard/catalog/hosting/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogHostingIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/physical/': {
      id: '/_dashboard/admin/dashboard/catalog/physical/'
      path: '/dashboard/catalog/physical'
      fullPath: '/admin/dashboard/catalog/physical/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogPhysicalIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/providers/': {
      id: '/_dashboard/admin/dashboard/catalog/providers/'
      path: '/dashboard/catalog/providers'
      fullPath: '/admin/dashboard/catalog/providers/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogProvidersIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/proxy/': {
      id: '/_dashboard/admin/dashboard/catalog/proxy/'
      path: '/dashboard/catalog/proxy'
      fullPath: '/admin/dashboard/catalog/proxy/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogProxyIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/proxy/new': {
      id: '/_dashboard/admin/dashboard/catalog/proxy/new'
      path: '/dashboard/catalog/proxy/new'
      fullPath: '/admin/dashboard/catalog/proxy/new'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogProxyNewRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/via/': {
      id: '/_dashboard/admin/dashboard/catalog/via/'
      path: '/dashboard/catalog/via'
      fullPath: '/admin/dashboard/catalog/via/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogViaIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/via/new': {
      id: '/_dashboard/admin/dashboard/catalog/via/new'
      path: '/dashboard/catalog/via/new'
      fullPath: '/admin/dashboard/catalog/via/new'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogViaNewRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/vps/': {
      id: '/_dashboard/admin/dashboard/catalog/vps/'
      path: '/dashboard/catalog/vps'
      fullPath: '/admin/dashboard/catalog/vps/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogVpsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/orders/$id/': {
      id: '/_dashboard/admin/dashboard/orders/$id/'
      path: '/dashboard/orders/$id'
      fullPath: '/admin/dashboard/orders/$id/'
      preLoaderRoute: typeof DashboardAdminDashboardOrdersIdIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/posts/categories/': {
      id: '/_dashboard/admin/dashboard/posts/categories/'
      path: '/dashboard/posts/categories'
      fullPath: '/admin/dashboard/posts/categories/'
      preLoaderRoute: typeof DashboardAdminDashboardPostsCategoriesIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/posts/new/': {
      id: '/_dashboard/admin/dashboard/posts/new/'
      path: '/dashboard/posts/new'
      fullPath: '/admin/dashboard/posts/new/'
      preLoaderRoute: typeof DashboardAdminDashboardPostsNewIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/posts/platforms/': {
      id: '/_dashboard/admin/dashboard/posts/platforms/'
      path: '/dashboard/posts/platforms'
      fullPath: '/admin/dashboard/posts/platforms/'
      preLoaderRoute: typeof DashboardAdminDashboardPostsPlatformsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/users/$userId/': {
      id: '/_dashboard/admin/dashboard/users/$userId/'
      path: '/dashboard/users/$userId'
      fullPath: '/admin/dashboard/users/$userId/'
      preLoaderRoute: typeof DashboardAdminDashboardUsersUserIdIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/users/roles/': {
      id: '/_dashboard/admin/dashboard/users/roles/'
      path: '/dashboard/users/roles'
      fullPath: '/admin/dashboard/users/roles/'
      preLoaderRoute: typeof DashboardAdminDashboardUsersRolesIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/hosting/$id/': {
      id: '/_dashboard/admin/dashboard/catalog/hosting/$id/'
      path: '/dashboard/catalog/hosting/$id'
      fullPath: '/admin/dashboard/catalog/hosting/$id/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogHostingIdIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/hosting/new/': {
      id: '/_dashboard/admin/dashboard/catalog/hosting/new/'
      path: '/dashboard/catalog/hosting/new'
      fullPath: '/admin/dashboard/catalog/hosting/new/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogHostingNewIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/physical/$id/': {
      id: '/_dashboard/admin/dashboard/catalog/physical/$id/'
      path: '/dashboard/catalog/physical/$id'
      fullPath: '/admin/dashboard/catalog/physical/$id/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogPhysicalIdIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/physical/new/': {
      id: '/_dashboard/admin/dashboard/catalog/physical/new/'
      path: '/dashboard/catalog/physical/new'
      fullPath: '/admin/dashboard/catalog/physical/new/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogPhysicalNewIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/proxy/$id/': {
      id: '/_dashboard/admin/dashboard/catalog/proxy/$id/'
      path: '/dashboard/catalog/proxy/$id'
      fullPath: '/admin/dashboard/catalog/proxy/$id/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogProxyIdIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/via/$id/': {
      id: '/_dashboard/admin/dashboard/catalog/via/$id/'
      path: '/dashboard/catalog/via/$id'
      fullPath: '/admin/dashboard/catalog/via/$id/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogViaIdIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/vps/$id/': {
      id: '/_dashboard/admin/dashboard/catalog/vps/$id/'
      path: '/dashboard/catalog/vps/$id'
      fullPath: '/admin/dashboard/catalog/vps/$id/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogVpsIdIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/vps/new/': {
      id: '/_dashboard/admin/dashboard/catalog/vps/new/'
      path: '/dashboard/catalog/vps/new'
      fullPath: '/admin/dashboard/catalog/vps/new/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogVpsNewIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/posts/$postId/edit/': {
      id: '/_dashboard/admin/dashboard/posts/$postId/edit/'
      path: '/dashboard/posts/$postId/edit'
      fullPath: '/admin/dashboard/posts/$postId/edit/'
      preLoaderRoute: typeof DashboardAdminDashboardPostsPostIdEditIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/hosting/$id/edit/': {
      id: '/_dashboard/admin/dashboard/catalog/hosting/$id/edit/'
      path: '/dashboard/catalog/hosting/$id/edit'
      fullPath: '/admin/dashboard/catalog/hosting/$id/edit/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogHostingIdEditIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/physical/$id/edit/': {
      id: '/_dashboard/admin/dashboard/catalog/physical/$id/edit/'
      path: '/dashboard/catalog/physical/$id/edit'
      fullPath: '/admin/dashboard/catalog/physical/$id/edit/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogPhysicalIdEditIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/proxy/$id/edit/': {
      id: '/_dashboard/admin/dashboard/catalog/proxy/$id/edit/'
      path: '/dashboard/catalog/proxy/$id/edit'
      fullPath: '/admin/dashboard/catalog/proxy/$id/edit/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogProxyIdEditIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/via/$id/edit/': {
      id: '/_dashboard/admin/dashboard/catalog/via/$id/edit/'
      path: '/dashboard/catalog/via/$id/edit'
      fullPath: '/admin/dashboard/catalog/via/$id/edit/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogViaIdEditIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/dashboard/catalog/vps/$id/edit/': {
      id: '/_dashboard/admin/dashboard/catalog/vps/$id/edit/'
      path: '/dashboard/catalog/vps/$id/edit'
      fullPath: '/admin/dashboard/catalog/vps/$id/edit/'
      preLoaderRoute: typeof DashboardAdminDashboardCatalogVpsIdEditIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminDashboardForbiddenRoute: typeof DashboardAdminDashboardForbiddenRoute
  DashboardAdminDashboardIndexRoute: typeof DashboardAdminDashboardIndexRoute
  DashboardAdminDashboardAuditLogsIndexRoute: typeof DashboardAdminDashboardAuditLogsIndexRoute
  DashboardAdminDashboardMediaIndexRoute: typeof DashboardAdminDashboardMediaIndexRoute
  DashboardAdminDashboardOrdersIndexRoute: typeof DashboardAdminDashboardOrdersIndexRoute
  DashboardAdminDashboardPostsIndexRoute: typeof DashboardAdminDashboardPostsIndexRoute
  DashboardAdminDashboardSettingsIndexRoute: typeof DashboardAdminDashboardSettingsIndexRoute
  DashboardAdminDashboardUsersIndexRoute: typeof DashboardAdminDashboardUsersIndexRoute
  DashboardAdminDashboardCatalogProxyNewRoute: typeof DashboardAdminDashboardCatalogProxyNewRoute
  DashboardAdminDashboardCatalogViaNewRoute: typeof DashboardAdminDashboardCatalogViaNewRoute
  DashboardAdminDashboardAppearanceMenuIndexRoute: typeof DashboardAdminDashboardAppearanceMenuIndexRoute
  DashboardAdminDashboardCatalogHostingIndexRoute: typeof DashboardAdminDashboardCatalogHostingIndexRoute
  DashboardAdminDashboardCatalogPhysicalIndexRoute: typeof DashboardAdminDashboardCatalogPhysicalIndexRoute
  DashboardAdminDashboardCatalogProvidersIndexRoute: typeof DashboardAdminDashboardCatalogProvidersIndexRoute
  DashboardAdminDashboardCatalogProxyIndexRoute: typeof DashboardAdminDashboardCatalogProxyIndexRoute
  DashboardAdminDashboardCatalogViaIndexRoute: typeof DashboardAdminDashboardCatalogViaIndexRoute
  DashboardAdminDashboardCatalogVpsIndexRoute: typeof DashboardAdminDashboardCatalogVpsIndexRoute
  DashboardAdminDashboardOrdersIdIndexRoute: typeof DashboardAdminDashboardOrdersIdIndexRoute
  DashboardAdminDashboardPostsCategoriesIndexRoute: typeof DashboardAdminDashboardPostsCategoriesIndexRoute
  DashboardAdminDashboardPostsNewIndexRoute: typeof DashboardAdminDashboardPostsNewIndexRoute
  DashboardAdminDashboardPostsPlatformsIndexRoute: typeof DashboardAdminDashboardPostsPlatformsIndexRoute
  DashboardAdminDashboardUsersUserIdIndexRoute: typeof DashboardAdminDashboardUsersUserIdIndexRoute
  DashboardAdminDashboardUsersRolesIndexRoute: typeof DashboardAdminDashboardUsersRolesIndexRoute
  DashboardAdminDashboardCatalogHostingIdIndexRoute: typeof DashboardAdminDashboardCatalogHostingIdIndexRoute
  DashboardAdminDashboardCatalogHostingNewIndexRoute: typeof DashboardAdminDashboardCatalogHostingNewIndexRoute
  DashboardAdminDashboardCatalogPhysicalIdIndexRoute: typeof DashboardAdminDashboardCatalogPhysicalIdIndexRoute
  DashboardAdminDashboardCatalogPhysicalNewIndexRoute: typeof DashboardAdminDashboardCatalogPhysicalNewIndexRoute
  DashboardAdminDashboardCatalogProxyIdIndexRoute: typeof DashboardAdminDashboardCatalogProxyIdIndexRoute
  DashboardAdminDashboardCatalogViaIdIndexRoute: typeof DashboardAdminDashboardCatalogViaIdIndexRoute
  DashboardAdminDashboardCatalogVpsIdIndexRoute: typeof DashboardAdminDashboardCatalogVpsIdIndexRoute
  DashboardAdminDashboardCatalogVpsNewIndexRoute: typeof DashboardAdminDashboardCatalogVpsNewIndexRoute
  DashboardAdminDashboardPostsPostIdEditIndexRoute: typeof DashboardAdminDashboardPostsPostIdEditIndexRoute
  DashboardAdminDashboardCatalogHostingIdEditIndexRoute: typeof DashboardAdminDashboardCatalogHostingIdEditIndexRoute
  DashboardAdminDashboardCatalogPhysicalIdEditIndexRoute: typeof DashboardAdminDashboardCatalogPhysicalIdEditIndexRoute
  DashboardAdminDashboardCatalogProxyIdEditIndexRoute: typeof DashboardAdminDashboardCatalogProxyIdEditIndexRoute
  DashboardAdminDashboardCatalogViaIdEditIndexRoute: typeof DashboardAdminDashboardCatalogViaIdEditIndexRoute
  DashboardAdminDashboardCatalogVpsIdEditIndexRoute: typeof DashboardAdminDashboardCatalogVpsIdEditIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminDashboardForbiddenRoute: DashboardAdminDashboardForbiddenRoute,
  DashboardAdminDashboardIndexRoute: DashboardAdminDashboardIndexRoute,
  DashboardAdminDashboardAuditLogsIndexRoute:
    DashboardAdminDashboardAuditLogsIndexRoute,
  DashboardAdminDashboardMediaIndexRoute:
    DashboardAdminDashboardMediaIndexRoute,
  DashboardAdminDashboardOrdersIndexRoute:
    DashboardAdminDashboardOrdersIndexRoute,
  DashboardAdminDashboardPostsIndexRoute:
    DashboardAdminDashboardPostsIndexRoute,
  DashboardAdminDashboardSettingsIndexRoute:
    DashboardAdminDashboardSettingsIndexRoute,
  DashboardAdminDashboardUsersIndexRoute:
    DashboardAdminDashboardUsersIndexRoute,
  DashboardAdminDashboardCatalogProxyNewRoute:
    DashboardAdminDashboardCatalogProxyNewRoute,
  DashboardAdminDashboardCatalogViaNewRoute:
    DashboardAdminDashboardCatalogViaNewRoute,
  DashboardAdminDashboardAppearanceMenuIndexRoute:
    DashboardAdminDashboardAppearanceMenuIndexRoute,
  DashboardAdminDashboardCatalogHostingIndexRoute:
    DashboardAdminDashboardCatalogHostingIndexRoute,
  DashboardAdminDashboardCatalogPhysicalIndexRoute:
    DashboardAdminDashboardCatalogPhysicalIndexRoute,
  DashboardAdminDashboardCatalogProvidersIndexRoute:
    DashboardAdminDashboardCatalogProvidersIndexRoute,
  DashboardAdminDashboardCatalogProxyIndexRoute:
    DashboardAdminDashboardCatalogProxyIndexRoute,
  DashboardAdminDashboardCatalogViaIndexRoute:
    DashboardAdminDashboardCatalogViaIndexRoute,
  DashboardAdminDashboardCatalogVpsIndexRoute:
    DashboardAdminDashboardCatalogVpsIndexRoute,
  DashboardAdminDashboardOrdersIdIndexRoute:
    DashboardAdminDashboardOrdersIdIndexRoute,
  DashboardAdminDashboardPostsCategoriesIndexRoute:
    DashboardAdminDashboardPostsCategoriesIndexRoute,
  DashboardAdminDashboardPostsNewIndexRoute:
    DashboardAdminDashboardPostsNewIndexRoute,
  DashboardAdminDashboardPostsPlatformsIndexRoute:
    DashboardAdminDashboardPostsPlatformsIndexRoute,
  DashboardAdminDashboardUsersUserIdIndexRoute:
    DashboardAdminDashboardUsersUserIdIndexRoute,
  DashboardAdminDashboardUsersRolesIndexRoute:
    DashboardAdminDashboardUsersRolesIndexRoute,
  DashboardAdminDashboardCatalogHostingIdIndexRoute:
    DashboardAdminDashboardCatalogHostingIdIndexRoute,
  DashboardAdminDashboardCatalogHostingNewIndexRoute:
    DashboardAdminDashboardCatalogHostingNewIndexRoute,
  DashboardAdminDashboardCatalogPhysicalIdIndexRoute:
    DashboardAdminDashboardCatalogPhysicalIdIndexRoute,
  DashboardAdminDashboardCatalogPhysicalNewIndexRoute:
    DashboardAdminDashboardCatalogPhysicalNewIndexRoute,
  DashboardAdminDashboardCatalogProxyIdIndexRoute:
    DashboardAdminDashboardCatalogProxyIdIndexRoute,
  DashboardAdminDashboardCatalogViaIdIndexRoute:
    DashboardAdminDashboardCatalogViaIdIndexRoute,
  DashboardAdminDashboardCatalogVpsIdIndexRoute:
    DashboardAdminDashboardCatalogVpsIdIndexRoute,
  DashboardAdminDashboardCatalogVpsNewIndexRoute:
    DashboardAdminDashboardCatalogVpsNewIndexRoute,
  DashboardAdminDashboardPostsPostIdEditIndexRoute:
    DashboardAdminDashboardPostsPostIdEditIndexRoute,
  DashboardAdminDashboardCatalogHostingIdEditIndexRoute:
    DashboardAdminDashboardCatalogHostingIdEditIndexRoute,
  DashboardAdminDashboardCatalogPhysicalIdEditIndexRoute:
    DashboardAdminDashboardCatalogPhysicalIdEditIndexRoute,
  DashboardAdminDashboardCatalogProxyIdEditIndexRoute:
    DashboardAdminDashboardCatalogProxyIdEditIndexRoute,
  DashboardAdminDashboardCatalogViaIdEditIndexRoute:
    DashboardAdminDashboardCatalogViaIdEditIndexRoute,
  DashboardAdminDashboardCatalogVpsIdEditIndexRoute:
    DashboardAdminDashboardCatalogVpsIdEditIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardCustomerRouteChildren {
  DashboardCustomerDashboardIndexRoute: typeof DashboardCustomerDashboardIndexRoute
  DashboardCustomerDashboardOrdersIdRoute: typeof DashboardCustomerDashboardOrdersIdRoute
  DashboardCustomerDashboardServicesIdRoute: typeof DashboardCustomerDashboardServicesIdRoute
  DashboardCustomerDashboardBuyIndexRoute: typeof DashboardCustomerDashboardBuyIndexRoute
  DashboardCustomerDashboardCartIndexRoute: typeof DashboardCustomerDashboardCartIndexRoute
  DashboardCustomerDashboardCheckoutIndexRoute: typeof DashboardCustomerDashboardCheckoutIndexRoute
  DashboardCustomerDashboardOrdersIndexRoute: typeof DashboardCustomerDashboardOrdersIndexRoute
  DashboardCustomerDashboardServicesIndexRoute: typeof DashboardCustomerDashboardServicesIndexRoute
}

const DashboardCustomerRouteChildren: DashboardCustomerRouteChildren = {
  DashboardCustomerDashboardIndexRoute: DashboardCustomerDashboardIndexRoute,
  DashboardCustomerDashboardOrdersIdRoute:
    DashboardCustomerDashboardOrdersIdRoute,
  DashboardCustomerDashboardServicesIdRoute:
    DashboardCustomerDashboardServicesIdRoute,
  DashboardCustomerDashboardBuyIndexRoute:
    DashboardCustomerDashboardBuyIndexRoute,
  DashboardCustomerDashboardCartIndexRoute:
    DashboardCustomerDashboardCartIndexRoute,
  DashboardCustomerDashboardCheckoutIndexRoute:
    DashboardCustomerDashboardCheckoutIndexRoute,
  DashboardCustomerDashboardOrdersIndexRoute:
    DashboardCustomerDashboardOrdersIndexRoute,
  DashboardCustomerDashboardServicesIndexRoute:
    DashboardCustomerDashboardServicesIndexRoute,
}

const DashboardCustomerRouteWithChildren =
  DashboardCustomerRoute._addFileChildren(DashboardCustomerRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardCustomerRoute: typeof DashboardCustomerRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardCustomerRoute: DashboardCustomerRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface authVerifyEmailRouteChildren {
  authVerifyEmailConfirmRoute: typeof authVerifyEmailConfirmRoute
}

const authVerifyEmailRouteChildren: authVerifyEmailRouteChildren = {
  authVerifyEmailConfirmRoute: authVerifyEmailConfirmRoute,
}

const authVerifyEmailRouteWithChildren = authVerifyEmailRoute._addFileChildren(
  authVerifyEmailRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
