/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authVerifyEmailConfirmRouteImport } from './routes/(auth)/verify-email.confirm'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardForbiddenRouteImport } from './routes/_dashboard/dashboard/forbidden'
import { Route as DashboardDashboardAuditLogsIndexRouteImport } from './routes/_dashboard/dashboard/audit-logs/index'
import { Route as DashboardDashboardMediaIndexRouteImport } from './routes/_dashboard/dashboard/media/index'
import { Route as DashboardDashboardPostsIndexRouteImport } from './routes/_dashboard/dashboard/posts/index'
import { Route as DashboardDashboardSettingsIndexRouteImport } from './routes/_dashboard/dashboard/settings/index'
import { Route as DashboardDashboardUsersIndexRouteImport } from './routes/_dashboard/dashboard/users/index'
import { Route as DashboardDashboardAppearanceMenuIndexRouteImport } from './routes/_dashboard/dashboard/appearance/menu/index'
import { Route as DashboardDashboardPostsCategoriesIndexRouteImport } from './routes/_dashboard/dashboard/posts/categories/index'
import { Route as DashboardDashboardPostsNewIndexRouteImport } from './routes/_dashboard/dashboard/posts/new/index'
import { Route as DashboardDashboardPostsPlatformsIndexRouteImport } from './routes/_dashboard/dashboard/posts/platforms/index'
import { Route as DashboardDashboardUsersUserIdIndexRouteImport } from './routes/_dashboard/dashboard/users/$userId/index'
import { Route as DashboardDashboardUsersRolesIndexRouteImport } from './routes/_dashboard/dashboard/users/roles/index'
import { Route as DashboardDashboardPostsPostIdEditIndexRouteImport } from './routes/_dashboard/dashboard/posts/$postId/edit/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailConfirmRoute = authVerifyEmailConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => authVerifyEmailRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardForbiddenRoute =
  DashboardDashboardForbiddenRouteImport.update({
    id: '/dashboard/forbidden',
    path: '/dashboard/forbidden',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAuditLogsIndexRoute =
  DashboardDashboardAuditLogsIndexRouteImport.update({
    id: '/dashboard/audit-logs/',
    path: '/dashboard/audit-logs/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardMediaIndexRoute =
  DashboardDashboardMediaIndexRouteImport.update({
    id: '/dashboard/media/',
    path: '/dashboard/media/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardPostsIndexRoute =
  DashboardDashboardPostsIndexRouteImport.update({
    id: '/dashboard/posts/',
    path: '/dashboard/posts/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsIndexRoute =
  DashboardDashboardSettingsIndexRouteImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardUsersIndexRoute =
  DashboardDashboardUsersIndexRouteImport.update({
    id: '/dashboard/users/',
    path: '/dashboard/users/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAppearanceMenuIndexRoute =
  DashboardDashboardAppearanceMenuIndexRouteImport.update({
    id: '/dashboard/appearance/menu/',
    path: '/dashboard/appearance/menu/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardPostsCategoriesIndexRoute =
  DashboardDashboardPostsCategoriesIndexRouteImport.update({
    id: '/dashboard/posts/categories/',
    path: '/dashboard/posts/categories/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardPostsNewIndexRoute =
  DashboardDashboardPostsNewIndexRouteImport.update({
    id: '/dashboard/posts/new/',
    path: '/dashboard/posts/new/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardPostsPlatformsIndexRoute =
  DashboardDashboardPostsPlatformsIndexRouteImport.update({
    id: '/dashboard/posts/platforms/',
    path: '/dashboard/posts/platforms/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardUsersUserIdIndexRoute =
  DashboardDashboardUsersUserIdIndexRouteImport.update({
    id: '/dashboard/users/$userId/',
    path: '/dashboard/users/$userId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardUsersRolesIndexRoute =
  DashboardDashboardUsersRolesIndexRouteImport.update({
    id: '/dashboard/users/roles/',
    path: '/dashboard/users/roles/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardPostsPostIdEditIndexRoute =
  DashboardDashboardPostsPostIdEditIndexRouteImport.update({
    id: '/dashboard/posts/$postId/edit/',
    path: '/dashboard/posts/$postId/edit/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRouteWithChildren
  '/verify-email/confirm': typeof authVerifyEmailConfirmRoute
  '/dashboard/forbidden': typeof DashboardDashboardForbiddenRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/audit-logs/': typeof DashboardDashboardAuditLogsIndexRoute
  '/dashboard/media/': typeof DashboardDashboardMediaIndexRoute
  '/dashboard/posts/': typeof DashboardDashboardPostsIndexRoute
  '/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
  '/dashboard/users/': typeof DashboardDashboardUsersIndexRoute
  '/dashboard/appearance/menu/': typeof DashboardDashboardAppearanceMenuIndexRoute
  '/dashboard/posts/categories/': typeof DashboardDashboardPostsCategoriesIndexRoute
  '/dashboard/posts/new/': typeof DashboardDashboardPostsNewIndexRoute
  '/dashboard/posts/platforms/': typeof DashboardDashboardPostsPlatformsIndexRoute
  '/dashboard/users/$userId/': typeof DashboardDashboardUsersUserIdIndexRoute
  '/dashboard/users/roles/': typeof DashboardDashboardUsersRolesIndexRoute
  '/dashboard/posts/$postId/edit/': typeof DashboardDashboardPostsPostIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRouteWithChildren
  '/verify-email/confirm': typeof authVerifyEmailConfirmRoute
  '/dashboard/forbidden': typeof DashboardDashboardForbiddenRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/audit-logs': typeof DashboardDashboardAuditLogsIndexRoute
  '/dashboard/media': typeof DashboardDashboardMediaIndexRoute
  '/dashboard/posts': typeof DashboardDashboardPostsIndexRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsIndexRoute
  '/dashboard/users': typeof DashboardDashboardUsersIndexRoute
  '/dashboard/appearance/menu': typeof DashboardDashboardAppearanceMenuIndexRoute
  '/dashboard/posts/categories': typeof DashboardDashboardPostsCategoriesIndexRoute
  '/dashboard/posts/new': typeof DashboardDashboardPostsNewIndexRoute
  '/dashboard/posts/platforms': typeof DashboardDashboardPostsPlatformsIndexRoute
  '/dashboard/users/$userId': typeof DashboardDashboardUsersUserIdIndexRoute
  '/dashboard/users/roles': typeof DashboardDashboardUsersRolesIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardDashboardPostsPostIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(auth)/verify-email/confirm': typeof authVerifyEmailConfirmRoute
  '/_dashboard/dashboard/forbidden': typeof DashboardDashboardForbiddenRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/audit-logs/': typeof DashboardDashboardAuditLogsIndexRoute
  '/_dashboard/dashboard/media/': typeof DashboardDashboardMediaIndexRoute
  '/_dashboard/dashboard/posts/': typeof DashboardDashboardPostsIndexRoute
  '/_dashboard/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
  '/_dashboard/dashboard/users/': typeof DashboardDashboardUsersIndexRoute
  '/_dashboard/dashboard/appearance/menu/': typeof DashboardDashboardAppearanceMenuIndexRoute
  '/_dashboard/dashboard/posts/categories/': typeof DashboardDashboardPostsCategoriesIndexRoute
  '/_dashboard/dashboard/posts/new/': typeof DashboardDashboardPostsNewIndexRoute
  '/_dashboard/dashboard/posts/platforms/': typeof DashboardDashboardPostsPlatformsIndexRoute
  '/_dashboard/dashboard/users/$userId/': typeof DashboardDashboardUsersUserIdIndexRoute
  '/_dashboard/dashboard/users/roles/': typeof DashboardDashboardUsersRolesIndexRoute
  '/_dashboard/dashboard/posts/$postId/edit/': typeof DashboardDashboardPostsPostIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-email/confirm'
    | '/dashboard/forbidden'
    | '/dashboard/'
    | '/dashboard/audit-logs/'
    | '/dashboard/media/'
    | '/dashboard/posts/'
    | '/dashboard/settings/'
    | '/dashboard/users/'
    | '/dashboard/appearance/menu/'
    | '/dashboard/posts/categories/'
    | '/dashboard/posts/new/'
    | '/dashboard/posts/platforms/'
    | '/dashboard/users/$userId/'
    | '/dashboard/users/roles/'
    | '/dashboard/posts/$postId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-email/confirm'
    | '/dashboard/forbidden'
    | '/dashboard'
    | '/dashboard/audit-logs'
    | '/dashboard/media'
    | '/dashboard/posts'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/appearance/menu'
    | '/dashboard/posts/categories'
    | '/dashboard/posts/new'
    | '/dashboard/posts/platforms'
    | '/dashboard/users/$userId'
    | '/dashboard/users/roles'
    | '/dashboard/posts/$postId/edit'
  id:
    | '__root__'
    | '/_dashboard'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/(public)/'
    | '/(auth)/verify-email/confirm'
    | '/_dashboard/dashboard/forbidden'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/audit-logs/'
    | '/_dashboard/dashboard/media/'
    | '/_dashboard/dashboard/posts/'
    | '/_dashboard/dashboard/settings/'
    | '/_dashboard/dashboard/users/'
    | '/_dashboard/dashboard/appearance/menu/'
    | '/_dashboard/dashboard/posts/categories/'
    | '/_dashboard/dashboard/posts/new/'
    | '/_dashboard/dashboard/posts/platforms/'
    | '/_dashboard/dashboard/users/$userId/'
    | '/_dashboard/dashboard/users/roles/'
    | '/_dashboard/dashboard/posts/$postId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email/confirm': {
      id: '/(auth)/verify-email/confirm'
      path: '/confirm'
      fullPath: '/verify-email/confirm'
      preLoaderRoute: typeof authVerifyEmailConfirmRouteImport
      parentRoute: typeof authVerifyEmailRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/forbidden': {
      id: '/_dashboard/dashboard/forbidden'
      path: '/dashboard/forbidden'
      fullPath: '/dashboard/forbidden'
      preLoaderRoute: typeof DashboardDashboardForbiddenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/audit-logs/': {
      id: '/_dashboard/dashboard/audit-logs/'
      path: '/dashboard/audit-logs'
      fullPath: '/dashboard/audit-logs/'
      preLoaderRoute: typeof DashboardDashboardAuditLogsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/media/': {
      id: '/_dashboard/dashboard/media/'
      path: '/dashboard/media'
      fullPath: '/dashboard/media/'
      preLoaderRoute: typeof DashboardDashboardMediaIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/posts/': {
      id: '/_dashboard/dashboard/posts/'
      path: '/dashboard/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardDashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings/': {
      id: '/_dashboard/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardDashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/users/': {
      id: '/_dashboard/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardDashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/appearance/menu/': {
      id: '/_dashboard/dashboard/appearance/menu/'
      path: '/dashboard/appearance/menu'
      fullPath: '/dashboard/appearance/menu/'
      preLoaderRoute: typeof DashboardDashboardAppearanceMenuIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/posts/categories/': {
      id: '/_dashboard/dashboard/posts/categories/'
      path: '/dashboard/posts/categories'
      fullPath: '/dashboard/posts/categories/'
      preLoaderRoute: typeof DashboardDashboardPostsCategoriesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/posts/new/': {
      id: '/_dashboard/dashboard/posts/new/'
      path: '/dashboard/posts/new'
      fullPath: '/dashboard/posts/new/'
      preLoaderRoute: typeof DashboardDashboardPostsNewIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/posts/platforms/': {
      id: '/_dashboard/dashboard/posts/platforms/'
      path: '/dashboard/posts/platforms'
      fullPath: '/dashboard/posts/platforms/'
      preLoaderRoute: typeof DashboardDashboardPostsPlatformsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/users/$userId/': {
      id: '/_dashboard/dashboard/users/$userId/'
      path: '/dashboard/users/$userId'
      fullPath: '/dashboard/users/$userId/'
      preLoaderRoute: typeof DashboardDashboardUsersUserIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/users/roles/': {
      id: '/_dashboard/dashboard/users/roles/'
      path: '/dashboard/users/roles'
      fullPath: '/dashboard/users/roles/'
      preLoaderRoute: typeof DashboardDashboardUsersRolesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/posts/$postId/edit/': {
      id: '/_dashboard/dashboard/posts/$postId/edit/'
      path: '/dashboard/posts/$postId/edit'
      fullPath: '/dashboard/posts/$postId/edit/'
      preLoaderRoute: typeof DashboardDashboardPostsPostIdEditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardForbiddenRoute: typeof DashboardDashboardForbiddenRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardAuditLogsIndexRoute: typeof DashboardDashboardAuditLogsIndexRoute
  DashboardDashboardMediaIndexRoute: typeof DashboardDashboardMediaIndexRoute
  DashboardDashboardPostsIndexRoute: typeof DashboardDashboardPostsIndexRoute
  DashboardDashboardSettingsIndexRoute: typeof DashboardDashboardSettingsIndexRoute
  DashboardDashboardUsersIndexRoute: typeof DashboardDashboardUsersIndexRoute
  DashboardDashboardAppearanceMenuIndexRoute: typeof DashboardDashboardAppearanceMenuIndexRoute
  DashboardDashboardPostsCategoriesIndexRoute: typeof DashboardDashboardPostsCategoriesIndexRoute
  DashboardDashboardPostsNewIndexRoute: typeof DashboardDashboardPostsNewIndexRoute
  DashboardDashboardPostsPlatformsIndexRoute: typeof DashboardDashboardPostsPlatformsIndexRoute
  DashboardDashboardUsersUserIdIndexRoute: typeof DashboardDashboardUsersUserIdIndexRoute
  DashboardDashboardUsersRolesIndexRoute: typeof DashboardDashboardUsersRolesIndexRoute
  DashboardDashboardPostsPostIdEditIndexRoute: typeof DashboardDashboardPostsPostIdEditIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardForbiddenRoute: DashboardDashboardForbiddenRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDashboardAuditLogsIndexRoute: DashboardDashboardAuditLogsIndexRoute,
  DashboardDashboardMediaIndexRoute: DashboardDashboardMediaIndexRoute,
  DashboardDashboardPostsIndexRoute: DashboardDashboardPostsIndexRoute,
  DashboardDashboardSettingsIndexRoute: DashboardDashboardSettingsIndexRoute,
  DashboardDashboardUsersIndexRoute: DashboardDashboardUsersIndexRoute,
  DashboardDashboardAppearanceMenuIndexRoute:
    DashboardDashboardAppearanceMenuIndexRoute,
  DashboardDashboardPostsCategoriesIndexRoute:
    DashboardDashboardPostsCategoriesIndexRoute,
  DashboardDashboardPostsNewIndexRoute: DashboardDashboardPostsNewIndexRoute,
  DashboardDashboardPostsPlatformsIndexRoute:
    DashboardDashboardPostsPlatformsIndexRoute,
  DashboardDashboardUsersUserIdIndexRoute:
    DashboardDashboardUsersUserIdIndexRoute,
  DashboardDashboardUsersRolesIndexRoute:
    DashboardDashboardUsersRolesIndexRoute,
  DashboardDashboardPostsPostIdEditIndexRoute:
    DashboardDashboardPostsPostIdEditIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface authVerifyEmailRouteChildren {
  authVerifyEmailConfirmRoute: typeof authVerifyEmailConfirmRoute
}

const authVerifyEmailRouteChildren: authVerifyEmailRouteChildren = {
  authVerifyEmailConfirmRoute: authVerifyEmailConfirmRoute,
}

const authVerifyEmailRouteWithChildren = authVerifyEmailRoute._addFileChildren(
  authVerifyEmailRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
