/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authVerifyEmailConfirmRouteImport } from './routes/(auth)/verify-email.confirm'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardForbiddenRouteImport } from './routes/_dashboard/dashboard/forbidden'
import { Route as DashboardDashboardAuditLogsIndexRouteImport } from './routes/_dashboard/dashboard/audit-logs/index'
import { Route as DashboardDashboardMediaIndexRouteImport } from './routes/_dashboard/dashboard/media/index'
import { Route as DashboardDashboardPostsIndexRouteImport } from './routes/_dashboard/dashboard/posts/index'
import { Route as DashboardDashboardSettingsIndexRouteImport } from './routes/_dashboard/dashboard/settings/index'
import { Route as DashboardDashboardUsersIndexRouteImport } from './routes/_dashboard/dashboard/users/index'
import { Route as DashboardDashboardAppearanceMenuIndexRouteImport } from './routes/_dashboard/dashboard/appearance/menu/index'
import { Route as DashboardDashboardCatalogHostingIndexRouteImport } from './routes/_dashboard/dashboard/catalog/hosting/index'
import { Route as DashboardDashboardCatalogPhysicalIndexRouteImport } from './routes/_dashboard/dashboard/catalog/physical/index'
import { Route as DashboardDashboardCatalogProvidersIndexRouteImport } from './routes/_dashboard/dashboard/catalog/providers/index'
import { Route as DashboardDashboardCatalogProxyIndexRouteImport } from './routes/_dashboard/dashboard/catalog/proxy/index'
import { Route as DashboardDashboardCatalogProxyNewRouteImport } from './routes/_dashboard/dashboard/catalog/proxy/new'
import { Route as DashboardDashboardCatalogViaIndexRouteImport } from './routes/_dashboard/dashboard/catalog/via/index'
import { Route as DashboardDashboardCatalogViaNewRouteImport } from './routes/_dashboard/dashboard/catalog/via/new'
import { Route as DashboardDashboardCatalogVpsIndexRouteImport } from './routes/_dashboard/dashboard/catalog/vps/index'
import { Route as DashboardDashboardPostsCategoriesIndexRouteImport } from './routes/_dashboard/dashboard/posts/categories/index'
import { Route as DashboardDashboardPostsNewIndexRouteImport } from './routes/_dashboard/dashboard/posts/new/index'
import { Route as DashboardDashboardPostsPlatformsIndexRouteImport } from './routes/_dashboard/dashboard/posts/platforms/index'
import { Route as DashboardDashboardUsersUserIdIndexRouteImport } from './routes/_dashboard/dashboard/users/$userId/index'
import { Route as DashboardDashboardUsersRolesIndexRouteImport } from './routes/_dashboard/dashboard/users/roles/index'
import { Route as DashboardDashboardCatalogHostingIdIndexRouteImport } from './routes/_dashboard/dashboard/catalog/hosting/$id/index'
import { Route as DashboardDashboardCatalogHostingNewIndexRouteImport } from './routes/_dashboard/dashboard/catalog/hosting/new/index'
import { Route as DashboardDashboardCatalogPhysicalIdIndexRouteImport } from './routes/_dashboard/dashboard/catalog/physical/$id/index'
import { Route as DashboardDashboardCatalogPhysicalNewIndexRouteImport } from './routes/_dashboard/dashboard/catalog/physical/new/index'
import { Route as DashboardDashboardCatalogProxyIdIndexRouteImport } from './routes/_dashboard/dashboard/catalog/proxy/$id/index'
import { Route as DashboardDashboardCatalogViaIdIndexRouteImport } from './routes/_dashboard/dashboard/catalog/via/$id/index'
import { Route as DashboardDashboardCatalogVpsIdIndexRouteImport } from './routes/_dashboard/dashboard/catalog/vps/$id/index'
import { Route as DashboardDashboardCatalogVpsNewIndexRouteImport } from './routes/_dashboard/dashboard/catalog/vps/new/index'
import { Route as DashboardDashboardPostsPostIdEditIndexRouteImport } from './routes/_dashboard/dashboard/posts/$postId/edit/index'
import { Route as DashboardDashboardCatalogHostingIdEditIndexRouteImport } from './routes/_dashboard/dashboard/catalog/hosting/$id/edit/index'
import { Route as DashboardDashboardCatalogPhysicalIdEditIndexRouteImport } from './routes/_dashboard/dashboard/catalog/physical/$id/edit/index'
import { Route as DashboardDashboardCatalogProxyIdEditIndexRouteImport } from './routes/_dashboard/dashboard/catalog/proxy/$id/edit/index'
import { Route as DashboardDashboardCatalogViaIdEditIndexRouteImport } from './routes/_dashboard/dashboard/catalog/via/$id/edit/index'
import { Route as DashboardDashboardCatalogVpsIdEditIndexRouteImport } from './routes/_dashboard/dashboard/catalog/vps/$id/edit/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailConfirmRoute = authVerifyEmailConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => authVerifyEmailRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardForbiddenRoute =
  DashboardDashboardForbiddenRouteImport.update({
    id: '/dashboard/forbidden',
    path: '/dashboard/forbidden',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAuditLogsIndexRoute =
  DashboardDashboardAuditLogsIndexRouteImport.update({
    id: '/dashboard/audit-logs/',
    path: '/dashboard/audit-logs/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardMediaIndexRoute =
  DashboardDashboardMediaIndexRouteImport.update({
    id: '/dashboard/media/',
    path: '/dashboard/media/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardPostsIndexRoute =
  DashboardDashboardPostsIndexRouteImport.update({
    id: '/dashboard/posts/',
    path: '/dashboard/posts/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsIndexRoute =
  DashboardDashboardSettingsIndexRouteImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardUsersIndexRoute =
  DashboardDashboardUsersIndexRouteImport.update({
    id: '/dashboard/users/',
    path: '/dashboard/users/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAppearanceMenuIndexRoute =
  DashboardDashboardAppearanceMenuIndexRouteImport.update({
    id: '/dashboard/appearance/menu/',
    path: '/dashboard/appearance/menu/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogHostingIndexRoute =
  DashboardDashboardCatalogHostingIndexRouteImport.update({
    id: '/dashboard/catalog/hosting/',
    path: '/dashboard/catalog/hosting/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogPhysicalIndexRoute =
  DashboardDashboardCatalogPhysicalIndexRouteImport.update({
    id: '/dashboard/catalog/physical/',
    path: '/dashboard/catalog/physical/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogProvidersIndexRoute =
  DashboardDashboardCatalogProvidersIndexRouteImport.update({
    id: '/dashboard/catalog/providers/',
    path: '/dashboard/catalog/providers/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogProxyIndexRoute =
  DashboardDashboardCatalogProxyIndexRouteImport.update({
    id: '/dashboard/catalog/proxy/',
    path: '/dashboard/catalog/proxy/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogProxyNewRoute =
  DashboardDashboardCatalogProxyNewRouteImport.update({
    id: '/dashboard/catalog/proxy/new',
    path: '/dashboard/catalog/proxy/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogViaIndexRoute =
  DashboardDashboardCatalogViaIndexRouteImport.update({
    id: '/dashboard/catalog/via/',
    path: '/dashboard/catalog/via/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogViaNewRoute =
  DashboardDashboardCatalogViaNewRouteImport.update({
    id: '/dashboard/catalog/via/new',
    path: '/dashboard/catalog/via/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogVpsIndexRoute =
  DashboardDashboardCatalogVpsIndexRouteImport.update({
    id: '/dashboard/catalog/vps/',
    path: '/dashboard/catalog/vps/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardPostsCategoriesIndexRoute =
  DashboardDashboardPostsCategoriesIndexRouteImport.update({
    id: '/dashboard/posts/categories/',
    path: '/dashboard/posts/categories/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardPostsNewIndexRoute =
  DashboardDashboardPostsNewIndexRouteImport.update({
    id: '/dashboard/posts/new/',
    path: '/dashboard/posts/new/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardPostsPlatformsIndexRoute =
  DashboardDashboardPostsPlatformsIndexRouteImport.update({
    id: '/dashboard/posts/platforms/',
    path: '/dashboard/posts/platforms/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardUsersUserIdIndexRoute =
  DashboardDashboardUsersUserIdIndexRouteImport.update({
    id: '/dashboard/users/$userId/',
    path: '/dashboard/users/$userId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardUsersRolesIndexRoute =
  DashboardDashboardUsersRolesIndexRouteImport.update({
    id: '/dashboard/users/roles/',
    path: '/dashboard/users/roles/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogHostingIdIndexRoute =
  DashboardDashboardCatalogHostingIdIndexRouteImport.update({
    id: '/dashboard/catalog/hosting/$id/',
    path: '/dashboard/catalog/hosting/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogHostingNewIndexRoute =
  DashboardDashboardCatalogHostingNewIndexRouteImport.update({
    id: '/dashboard/catalog/hosting/new/',
    path: '/dashboard/catalog/hosting/new/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogPhysicalIdIndexRoute =
  DashboardDashboardCatalogPhysicalIdIndexRouteImport.update({
    id: '/dashboard/catalog/physical/$id/',
    path: '/dashboard/catalog/physical/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogPhysicalNewIndexRoute =
  DashboardDashboardCatalogPhysicalNewIndexRouteImport.update({
    id: '/dashboard/catalog/physical/new/',
    path: '/dashboard/catalog/physical/new/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogProxyIdIndexRoute =
  DashboardDashboardCatalogProxyIdIndexRouteImport.update({
    id: '/dashboard/catalog/proxy/$id/',
    path: '/dashboard/catalog/proxy/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogViaIdIndexRoute =
  DashboardDashboardCatalogViaIdIndexRouteImport.update({
    id: '/dashboard/catalog/via/$id/',
    path: '/dashboard/catalog/via/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogVpsIdIndexRoute =
  DashboardDashboardCatalogVpsIdIndexRouteImport.update({
    id: '/dashboard/catalog/vps/$id/',
    path: '/dashboard/catalog/vps/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogVpsNewIndexRoute =
  DashboardDashboardCatalogVpsNewIndexRouteImport.update({
    id: '/dashboard/catalog/vps/new/',
    path: '/dashboard/catalog/vps/new/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardPostsPostIdEditIndexRoute =
  DashboardDashboardPostsPostIdEditIndexRouteImport.update({
    id: '/dashboard/posts/$postId/edit/',
    path: '/dashboard/posts/$postId/edit/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogHostingIdEditIndexRoute =
  DashboardDashboardCatalogHostingIdEditIndexRouteImport.update({
    id: '/dashboard/catalog/hosting/$id/edit/',
    path: '/dashboard/catalog/hosting/$id/edit/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogPhysicalIdEditIndexRoute =
  DashboardDashboardCatalogPhysicalIdEditIndexRouteImport.update({
    id: '/dashboard/catalog/physical/$id/edit/',
    path: '/dashboard/catalog/physical/$id/edit/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogProxyIdEditIndexRoute =
  DashboardDashboardCatalogProxyIdEditIndexRouteImport.update({
    id: '/dashboard/catalog/proxy/$id/edit/',
    path: '/dashboard/catalog/proxy/$id/edit/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogViaIdEditIndexRoute =
  DashboardDashboardCatalogViaIdEditIndexRouteImport.update({
    id: '/dashboard/catalog/via/$id/edit/',
    path: '/dashboard/catalog/via/$id/edit/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCatalogVpsIdEditIndexRoute =
  DashboardDashboardCatalogVpsIdEditIndexRouteImport.update({
    id: '/dashboard/catalog/vps/$id/edit/',
    path: '/dashboard/catalog/vps/$id/edit/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRouteWithChildren
  '/verify-email/confirm': typeof authVerifyEmailConfirmRoute
  '/dashboard/forbidden': typeof DashboardDashboardForbiddenRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/audit-logs/': typeof DashboardDashboardAuditLogsIndexRoute
  '/dashboard/media/': typeof DashboardDashboardMediaIndexRoute
  '/dashboard/posts/': typeof DashboardDashboardPostsIndexRoute
  '/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
  '/dashboard/users/': typeof DashboardDashboardUsersIndexRoute
  '/dashboard/catalog/proxy/new': typeof DashboardDashboardCatalogProxyNewRoute
  '/dashboard/catalog/via/new': typeof DashboardDashboardCatalogViaNewRoute
  '/dashboard/appearance/menu/': typeof DashboardDashboardAppearanceMenuIndexRoute
  '/dashboard/catalog/hosting/': typeof DashboardDashboardCatalogHostingIndexRoute
  '/dashboard/catalog/physical/': typeof DashboardDashboardCatalogPhysicalIndexRoute
  '/dashboard/catalog/providers/': typeof DashboardDashboardCatalogProvidersIndexRoute
  '/dashboard/catalog/proxy/': typeof DashboardDashboardCatalogProxyIndexRoute
  '/dashboard/catalog/via/': typeof DashboardDashboardCatalogViaIndexRoute
  '/dashboard/catalog/vps/': typeof DashboardDashboardCatalogVpsIndexRoute
  '/dashboard/posts/categories/': typeof DashboardDashboardPostsCategoriesIndexRoute
  '/dashboard/posts/new/': typeof DashboardDashboardPostsNewIndexRoute
  '/dashboard/posts/platforms/': typeof DashboardDashboardPostsPlatformsIndexRoute
  '/dashboard/users/$userId/': typeof DashboardDashboardUsersUserIdIndexRoute
  '/dashboard/users/roles/': typeof DashboardDashboardUsersRolesIndexRoute
  '/dashboard/catalog/hosting/$id/': typeof DashboardDashboardCatalogHostingIdIndexRoute
  '/dashboard/catalog/hosting/new/': typeof DashboardDashboardCatalogHostingNewIndexRoute
  '/dashboard/catalog/physical/$id/': typeof DashboardDashboardCatalogPhysicalIdIndexRoute
  '/dashboard/catalog/physical/new/': typeof DashboardDashboardCatalogPhysicalNewIndexRoute
  '/dashboard/catalog/proxy/$id/': typeof DashboardDashboardCatalogProxyIdIndexRoute
  '/dashboard/catalog/via/$id/': typeof DashboardDashboardCatalogViaIdIndexRoute
  '/dashboard/catalog/vps/$id/': typeof DashboardDashboardCatalogVpsIdIndexRoute
  '/dashboard/catalog/vps/new/': typeof DashboardDashboardCatalogVpsNewIndexRoute
  '/dashboard/posts/$postId/edit/': typeof DashboardDashboardPostsPostIdEditIndexRoute
  '/dashboard/catalog/hosting/$id/edit/': typeof DashboardDashboardCatalogHostingIdEditIndexRoute
  '/dashboard/catalog/physical/$id/edit/': typeof DashboardDashboardCatalogPhysicalIdEditIndexRoute
  '/dashboard/catalog/proxy/$id/edit/': typeof DashboardDashboardCatalogProxyIdEditIndexRoute
  '/dashboard/catalog/via/$id/edit/': typeof DashboardDashboardCatalogViaIdEditIndexRoute
  '/dashboard/catalog/vps/$id/edit/': typeof DashboardDashboardCatalogVpsIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRouteWithChildren
  '/verify-email/confirm': typeof authVerifyEmailConfirmRoute
  '/dashboard/forbidden': typeof DashboardDashboardForbiddenRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/audit-logs': typeof DashboardDashboardAuditLogsIndexRoute
  '/dashboard/media': typeof DashboardDashboardMediaIndexRoute
  '/dashboard/posts': typeof DashboardDashboardPostsIndexRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsIndexRoute
  '/dashboard/users': typeof DashboardDashboardUsersIndexRoute
  '/dashboard/catalog/proxy/new': typeof DashboardDashboardCatalogProxyNewRoute
  '/dashboard/catalog/via/new': typeof DashboardDashboardCatalogViaNewRoute
  '/dashboard/appearance/menu': typeof DashboardDashboardAppearanceMenuIndexRoute
  '/dashboard/catalog/hosting': typeof DashboardDashboardCatalogHostingIndexRoute
  '/dashboard/catalog/physical': typeof DashboardDashboardCatalogPhysicalIndexRoute
  '/dashboard/catalog/providers': typeof DashboardDashboardCatalogProvidersIndexRoute
  '/dashboard/catalog/proxy': typeof DashboardDashboardCatalogProxyIndexRoute
  '/dashboard/catalog/via': typeof DashboardDashboardCatalogViaIndexRoute
  '/dashboard/catalog/vps': typeof DashboardDashboardCatalogVpsIndexRoute
  '/dashboard/posts/categories': typeof DashboardDashboardPostsCategoriesIndexRoute
  '/dashboard/posts/new': typeof DashboardDashboardPostsNewIndexRoute
  '/dashboard/posts/platforms': typeof DashboardDashboardPostsPlatformsIndexRoute
  '/dashboard/users/$userId': typeof DashboardDashboardUsersUserIdIndexRoute
  '/dashboard/users/roles': typeof DashboardDashboardUsersRolesIndexRoute
  '/dashboard/catalog/hosting/$id': typeof DashboardDashboardCatalogHostingIdIndexRoute
  '/dashboard/catalog/hosting/new': typeof DashboardDashboardCatalogHostingNewIndexRoute
  '/dashboard/catalog/physical/$id': typeof DashboardDashboardCatalogPhysicalIdIndexRoute
  '/dashboard/catalog/physical/new': typeof DashboardDashboardCatalogPhysicalNewIndexRoute
  '/dashboard/catalog/proxy/$id': typeof DashboardDashboardCatalogProxyIdIndexRoute
  '/dashboard/catalog/via/$id': typeof DashboardDashboardCatalogViaIdIndexRoute
  '/dashboard/catalog/vps/$id': typeof DashboardDashboardCatalogVpsIdIndexRoute
  '/dashboard/catalog/vps/new': typeof DashboardDashboardCatalogVpsNewIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardDashboardPostsPostIdEditIndexRoute
  '/dashboard/catalog/hosting/$id/edit': typeof DashboardDashboardCatalogHostingIdEditIndexRoute
  '/dashboard/catalog/physical/$id/edit': typeof DashboardDashboardCatalogPhysicalIdEditIndexRoute
  '/dashboard/catalog/proxy/$id/edit': typeof DashboardDashboardCatalogProxyIdEditIndexRoute
  '/dashboard/catalog/via/$id/edit': typeof DashboardDashboardCatalogViaIdEditIndexRoute
  '/dashboard/catalog/vps/$id/edit': typeof DashboardDashboardCatalogVpsIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(auth)/verify-email/confirm': typeof authVerifyEmailConfirmRoute
  '/_dashboard/dashboard/forbidden': typeof DashboardDashboardForbiddenRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/audit-logs/': typeof DashboardDashboardAuditLogsIndexRoute
  '/_dashboard/dashboard/media/': typeof DashboardDashboardMediaIndexRoute
  '/_dashboard/dashboard/posts/': typeof DashboardDashboardPostsIndexRoute
  '/_dashboard/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
  '/_dashboard/dashboard/users/': typeof DashboardDashboardUsersIndexRoute
  '/_dashboard/dashboard/catalog/proxy/new': typeof DashboardDashboardCatalogProxyNewRoute
  '/_dashboard/dashboard/catalog/via/new': typeof DashboardDashboardCatalogViaNewRoute
  '/_dashboard/dashboard/appearance/menu/': typeof DashboardDashboardAppearanceMenuIndexRoute
  '/_dashboard/dashboard/catalog/hosting/': typeof DashboardDashboardCatalogHostingIndexRoute
  '/_dashboard/dashboard/catalog/physical/': typeof DashboardDashboardCatalogPhysicalIndexRoute
  '/_dashboard/dashboard/catalog/providers/': typeof DashboardDashboardCatalogProvidersIndexRoute
  '/_dashboard/dashboard/catalog/proxy/': typeof DashboardDashboardCatalogProxyIndexRoute
  '/_dashboard/dashboard/catalog/via/': typeof DashboardDashboardCatalogViaIndexRoute
  '/_dashboard/dashboard/catalog/vps/': typeof DashboardDashboardCatalogVpsIndexRoute
  '/_dashboard/dashboard/posts/categories/': typeof DashboardDashboardPostsCategoriesIndexRoute
  '/_dashboard/dashboard/posts/new/': typeof DashboardDashboardPostsNewIndexRoute
  '/_dashboard/dashboard/posts/platforms/': typeof DashboardDashboardPostsPlatformsIndexRoute
  '/_dashboard/dashboard/users/$userId/': typeof DashboardDashboardUsersUserIdIndexRoute
  '/_dashboard/dashboard/users/roles/': typeof DashboardDashboardUsersRolesIndexRoute
  '/_dashboard/dashboard/catalog/hosting/$id/': typeof DashboardDashboardCatalogHostingIdIndexRoute
  '/_dashboard/dashboard/catalog/hosting/new/': typeof DashboardDashboardCatalogHostingNewIndexRoute
  '/_dashboard/dashboard/catalog/physical/$id/': typeof DashboardDashboardCatalogPhysicalIdIndexRoute
  '/_dashboard/dashboard/catalog/physical/new/': typeof DashboardDashboardCatalogPhysicalNewIndexRoute
  '/_dashboard/dashboard/catalog/proxy/$id/': typeof DashboardDashboardCatalogProxyIdIndexRoute
  '/_dashboard/dashboard/catalog/via/$id/': typeof DashboardDashboardCatalogViaIdIndexRoute
  '/_dashboard/dashboard/catalog/vps/$id/': typeof DashboardDashboardCatalogVpsIdIndexRoute
  '/_dashboard/dashboard/catalog/vps/new/': typeof DashboardDashboardCatalogVpsNewIndexRoute
  '/_dashboard/dashboard/posts/$postId/edit/': typeof DashboardDashboardPostsPostIdEditIndexRoute
  '/_dashboard/dashboard/catalog/hosting/$id/edit/': typeof DashboardDashboardCatalogHostingIdEditIndexRoute
  '/_dashboard/dashboard/catalog/physical/$id/edit/': typeof DashboardDashboardCatalogPhysicalIdEditIndexRoute
  '/_dashboard/dashboard/catalog/proxy/$id/edit/': typeof DashboardDashboardCatalogProxyIdEditIndexRoute
  '/_dashboard/dashboard/catalog/via/$id/edit/': typeof DashboardDashboardCatalogViaIdEditIndexRoute
  '/_dashboard/dashboard/catalog/vps/$id/edit/': typeof DashboardDashboardCatalogVpsIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-email/confirm'
    | '/dashboard/forbidden'
    | '/dashboard/'
    | '/dashboard/audit-logs/'
    | '/dashboard/media/'
    | '/dashboard/posts/'
    | '/dashboard/settings/'
    | '/dashboard/users/'
    | '/dashboard/catalog/proxy/new'
    | '/dashboard/catalog/via/new'
    | '/dashboard/appearance/menu/'
    | '/dashboard/catalog/hosting/'
    | '/dashboard/catalog/physical/'
    | '/dashboard/catalog/providers/'
    | '/dashboard/catalog/proxy/'
    | '/dashboard/catalog/via/'
    | '/dashboard/catalog/vps/'
    | '/dashboard/posts/categories/'
    | '/dashboard/posts/new/'
    | '/dashboard/posts/platforms/'
    | '/dashboard/users/$userId/'
    | '/dashboard/users/roles/'
    | '/dashboard/catalog/hosting/$id/'
    | '/dashboard/catalog/hosting/new/'
    | '/dashboard/catalog/physical/$id/'
    | '/dashboard/catalog/physical/new/'
    | '/dashboard/catalog/proxy/$id/'
    | '/dashboard/catalog/via/$id/'
    | '/dashboard/catalog/vps/$id/'
    | '/dashboard/catalog/vps/new/'
    | '/dashboard/posts/$postId/edit/'
    | '/dashboard/catalog/hosting/$id/edit/'
    | '/dashboard/catalog/physical/$id/edit/'
    | '/dashboard/catalog/proxy/$id/edit/'
    | '/dashboard/catalog/via/$id/edit/'
    | '/dashboard/catalog/vps/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-email/confirm'
    | '/dashboard/forbidden'
    | '/dashboard'
    | '/dashboard/audit-logs'
    | '/dashboard/media'
    | '/dashboard/posts'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/catalog/proxy/new'
    | '/dashboard/catalog/via/new'
    | '/dashboard/appearance/menu'
    | '/dashboard/catalog/hosting'
    | '/dashboard/catalog/physical'
    | '/dashboard/catalog/providers'
    | '/dashboard/catalog/proxy'
    | '/dashboard/catalog/via'
    | '/dashboard/catalog/vps'
    | '/dashboard/posts/categories'
    | '/dashboard/posts/new'
    | '/dashboard/posts/platforms'
    | '/dashboard/users/$userId'
    | '/dashboard/users/roles'
    | '/dashboard/catalog/hosting/$id'
    | '/dashboard/catalog/hosting/new'
    | '/dashboard/catalog/physical/$id'
    | '/dashboard/catalog/physical/new'
    | '/dashboard/catalog/proxy/$id'
    | '/dashboard/catalog/via/$id'
    | '/dashboard/catalog/vps/$id'
    | '/dashboard/catalog/vps/new'
    | '/dashboard/posts/$postId/edit'
    | '/dashboard/catalog/hosting/$id/edit'
    | '/dashboard/catalog/physical/$id/edit'
    | '/dashboard/catalog/proxy/$id/edit'
    | '/dashboard/catalog/via/$id/edit'
    | '/dashboard/catalog/vps/$id/edit'
  id:
    | '__root__'
    | '/_dashboard'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/(public)/'
    | '/(auth)/verify-email/confirm'
    | '/_dashboard/dashboard/forbidden'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/audit-logs/'
    | '/_dashboard/dashboard/media/'
    | '/_dashboard/dashboard/posts/'
    | '/_dashboard/dashboard/settings/'
    | '/_dashboard/dashboard/users/'
    | '/_dashboard/dashboard/catalog/proxy/new'
    | '/_dashboard/dashboard/catalog/via/new'
    | '/_dashboard/dashboard/appearance/menu/'
    | '/_dashboard/dashboard/catalog/hosting/'
    | '/_dashboard/dashboard/catalog/physical/'
    | '/_dashboard/dashboard/catalog/providers/'
    | '/_dashboard/dashboard/catalog/proxy/'
    | '/_dashboard/dashboard/catalog/via/'
    | '/_dashboard/dashboard/catalog/vps/'
    | '/_dashboard/dashboard/posts/categories/'
    | '/_dashboard/dashboard/posts/new/'
    | '/_dashboard/dashboard/posts/platforms/'
    | '/_dashboard/dashboard/users/$userId/'
    | '/_dashboard/dashboard/users/roles/'
    | '/_dashboard/dashboard/catalog/hosting/$id/'
    | '/_dashboard/dashboard/catalog/hosting/new/'
    | '/_dashboard/dashboard/catalog/physical/$id/'
    | '/_dashboard/dashboard/catalog/physical/new/'
    | '/_dashboard/dashboard/catalog/proxy/$id/'
    | '/_dashboard/dashboard/catalog/via/$id/'
    | '/_dashboard/dashboard/catalog/vps/$id/'
    | '/_dashboard/dashboard/catalog/vps/new/'
    | '/_dashboard/dashboard/posts/$postId/edit/'
    | '/_dashboard/dashboard/catalog/hosting/$id/edit/'
    | '/_dashboard/dashboard/catalog/physical/$id/edit/'
    | '/_dashboard/dashboard/catalog/proxy/$id/edit/'
    | '/_dashboard/dashboard/catalog/via/$id/edit/'
    | '/_dashboard/dashboard/catalog/vps/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email/confirm': {
      id: '/(auth)/verify-email/confirm'
      path: '/confirm'
      fullPath: '/verify-email/confirm'
      preLoaderRoute: typeof authVerifyEmailConfirmRouteImport
      parentRoute: typeof authVerifyEmailRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/forbidden': {
      id: '/_dashboard/dashboard/forbidden'
      path: '/dashboard/forbidden'
      fullPath: '/dashboard/forbidden'
      preLoaderRoute: typeof DashboardDashboardForbiddenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/audit-logs/': {
      id: '/_dashboard/dashboard/audit-logs/'
      path: '/dashboard/audit-logs'
      fullPath: '/dashboard/audit-logs/'
      preLoaderRoute: typeof DashboardDashboardAuditLogsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/media/': {
      id: '/_dashboard/dashboard/media/'
      path: '/dashboard/media'
      fullPath: '/dashboard/media/'
      preLoaderRoute: typeof DashboardDashboardMediaIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/posts/': {
      id: '/_dashboard/dashboard/posts/'
      path: '/dashboard/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardDashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings/': {
      id: '/_dashboard/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardDashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/users/': {
      id: '/_dashboard/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardDashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/appearance/menu/': {
      id: '/_dashboard/dashboard/appearance/menu/'
      path: '/dashboard/appearance/menu'
      fullPath: '/dashboard/appearance/menu/'
      preLoaderRoute: typeof DashboardDashboardAppearanceMenuIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/hosting/': {
      id: '/_dashboard/dashboard/catalog/hosting/'
      path: '/dashboard/catalog/hosting'
      fullPath: '/dashboard/catalog/hosting/'
      preLoaderRoute: typeof DashboardDashboardCatalogHostingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/physical/': {
      id: '/_dashboard/dashboard/catalog/physical/'
      path: '/dashboard/catalog/physical'
      fullPath: '/dashboard/catalog/physical/'
      preLoaderRoute: typeof DashboardDashboardCatalogPhysicalIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/providers/': {
      id: '/_dashboard/dashboard/catalog/providers/'
      path: '/dashboard/catalog/providers'
      fullPath: '/dashboard/catalog/providers/'
      preLoaderRoute: typeof DashboardDashboardCatalogProvidersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/proxy/': {
      id: '/_dashboard/dashboard/catalog/proxy/'
      path: '/dashboard/catalog/proxy'
      fullPath: '/dashboard/catalog/proxy/'
      preLoaderRoute: typeof DashboardDashboardCatalogProxyIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/proxy/new': {
      id: '/_dashboard/dashboard/catalog/proxy/new'
      path: '/dashboard/catalog/proxy/new'
      fullPath: '/dashboard/catalog/proxy/new'
      preLoaderRoute: typeof DashboardDashboardCatalogProxyNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/via/': {
      id: '/_dashboard/dashboard/catalog/via/'
      path: '/dashboard/catalog/via'
      fullPath: '/dashboard/catalog/via/'
      preLoaderRoute: typeof DashboardDashboardCatalogViaIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/via/new': {
      id: '/_dashboard/dashboard/catalog/via/new'
      path: '/dashboard/catalog/via/new'
      fullPath: '/dashboard/catalog/via/new'
      preLoaderRoute: typeof DashboardDashboardCatalogViaNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/vps/': {
      id: '/_dashboard/dashboard/catalog/vps/'
      path: '/dashboard/catalog/vps'
      fullPath: '/dashboard/catalog/vps/'
      preLoaderRoute: typeof DashboardDashboardCatalogVpsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/posts/categories/': {
      id: '/_dashboard/dashboard/posts/categories/'
      path: '/dashboard/posts/categories'
      fullPath: '/dashboard/posts/categories/'
      preLoaderRoute: typeof DashboardDashboardPostsCategoriesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/posts/new/': {
      id: '/_dashboard/dashboard/posts/new/'
      path: '/dashboard/posts/new'
      fullPath: '/dashboard/posts/new/'
      preLoaderRoute: typeof DashboardDashboardPostsNewIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/posts/platforms/': {
      id: '/_dashboard/dashboard/posts/platforms/'
      path: '/dashboard/posts/platforms'
      fullPath: '/dashboard/posts/platforms/'
      preLoaderRoute: typeof DashboardDashboardPostsPlatformsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/users/$userId/': {
      id: '/_dashboard/dashboard/users/$userId/'
      path: '/dashboard/users/$userId'
      fullPath: '/dashboard/users/$userId/'
      preLoaderRoute: typeof DashboardDashboardUsersUserIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/users/roles/': {
      id: '/_dashboard/dashboard/users/roles/'
      path: '/dashboard/users/roles'
      fullPath: '/dashboard/users/roles/'
      preLoaderRoute: typeof DashboardDashboardUsersRolesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/hosting/$id/': {
      id: '/_dashboard/dashboard/catalog/hosting/$id/'
      path: '/dashboard/catalog/hosting/$id'
      fullPath: '/dashboard/catalog/hosting/$id/'
      preLoaderRoute: typeof DashboardDashboardCatalogHostingIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/hosting/new/': {
      id: '/_dashboard/dashboard/catalog/hosting/new/'
      path: '/dashboard/catalog/hosting/new'
      fullPath: '/dashboard/catalog/hosting/new/'
      preLoaderRoute: typeof DashboardDashboardCatalogHostingNewIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/physical/$id/': {
      id: '/_dashboard/dashboard/catalog/physical/$id/'
      path: '/dashboard/catalog/physical/$id'
      fullPath: '/dashboard/catalog/physical/$id/'
      preLoaderRoute: typeof DashboardDashboardCatalogPhysicalIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/physical/new/': {
      id: '/_dashboard/dashboard/catalog/physical/new/'
      path: '/dashboard/catalog/physical/new'
      fullPath: '/dashboard/catalog/physical/new/'
      preLoaderRoute: typeof DashboardDashboardCatalogPhysicalNewIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/proxy/$id/': {
      id: '/_dashboard/dashboard/catalog/proxy/$id/'
      path: '/dashboard/catalog/proxy/$id'
      fullPath: '/dashboard/catalog/proxy/$id/'
      preLoaderRoute: typeof DashboardDashboardCatalogProxyIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/via/$id/': {
      id: '/_dashboard/dashboard/catalog/via/$id/'
      path: '/dashboard/catalog/via/$id'
      fullPath: '/dashboard/catalog/via/$id/'
      preLoaderRoute: typeof DashboardDashboardCatalogViaIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/vps/$id/': {
      id: '/_dashboard/dashboard/catalog/vps/$id/'
      path: '/dashboard/catalog/vps/$id'
      fullPath: '/dashboard/catalog/vps/$id/'
      preLoaderRoute: typeof DashboardDashboardCatalogVpsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/vps/new/': {
      id: '/_dashboard/dashboard/catalog/vps/new/'
      path: '/dashboard/catalog/vps/new'
      fullPath: '/dashboard/catalog/vps/new/'
      preLoaderRoute: typeof DashboardDashboardCatalogVpsNewIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/posts/$postId/edit/': {
      id: '/_dashboard/dashboard/posts/$postId/edit/'
      path: '/dashboard/posts/$postId/edit'
      fullPath: '/dashboard/posts/$postId/edit/'
      preLoaderRoute: typeof DashboardDashboardPostsPostIdEditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/hosting/$id/edit/': {
      id: '/_dashboard/dashboard/catalog/hosting/$id/edit/'
      path: '/dashboard/catalog/hosting/$id/edit'
      fullPath: '/dashboard/catalog/hosting/$id/edit/'
      preLoaderRoute: typeof DashboardDashboardCatalogHostingIdEditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/physical/$id/edit/': {
      id: '/_dashboard/dashboard/catalog/physical/$id/edit/'
      path: '/dashboard/catalog/physical/$id/edit'
      fullPath: '/dashboard/catalog/physical/$id/edit/'
      preLoaderRoute: typeof DashboardDashboardCatalogPhysicalIdEditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/proxy/$id/edit/': {
      id: '/_dashboard/dashboard/catalog/proxy/$id/edit/'
      path: '/dashboard/catalog/proxy/$id/edit'
      fullPath: '/dashboard/catalog/proxy/$id/edit/'
      preLoaderRoute: typeof DashboardDashboardCatalogProxyIdEditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/via/$id/edit/': {
      id: '/_dashboard/dashboard/catalog/via/$id/edit/'
      path: '/dashboard/catalog/via/$id/edit'
      fullPath: '/dashboard/catalog/via/$id/edit/'
      preLoaderRoute: typeof DashboardDashboardCatalogViaIdEditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/catalog/vps/$id/edit/': {
      id: '/_dashboard/dashboard/catalog/vps/$id/edit/'
      path: '/dashboard/catalog/vps/$id/edit'
      fullPath: '/dashboard/catalog/vps/$id/edit/'
      preLoaderRoute: typeof DashboardDashboardCatalogVpsIdEditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardForbiddenRoute: typeof DashboardDashboardForbiddenRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardAuditLogsIndexRoute: typeof DashboardDashboardAuditLogsIndexRoute
  DashboardDashboardMediaIndexRoute: typeof DashboardDashboardMediaIndexRoute
  DashboardDashboardPostsIndexRoute: typeof DashboardDashboardPostsIndexRoute
  DashboardDashboardSettingsIndexRoute: typeof DashboardDashboardSettingsIndexRoute
  DashboardDashboardUsersIndexRoute: typeof DashboardDashboardUsersIndexRoute
  DashboardDashboardCatalogProxyNewRoute: typeof DashboardDashboardCatalogProxyNewRoute
  DashboardDashboardCatalogViaNewRoute: typeof DashboardDashboardCatalogViaNewRoute
  DashboardDashboardAppearanceMenuIndexRoute: typeof DashboardDashboardAppearanceMenuIndexRoute
  DashboardDashboardCatalogHostingIndexRoute: typeof DashboardDashboardCatalogHostingIndexRoute
  DashboardDashboardCatalogPhysicalIndexRoute: typeof DashboardDashboardCatalogPhysicalIndexRoute
  DashboardDashboardCatalogProvidersIndexRoute: typeof DashboardDashboardCatalogProvidersIndexRoute
  DashboardDashboardCatalogProxyIndexRoute: typeof DashboardDashboardCatalogProxyIndexRoute
  DashboardDashboardCatalogViaIndexRoute: typeof DashboardDashboardCatalogViaIndexRoute
  DashboardDashboardCatalogVpsIndexRoute: typeof DashboardDashboardCatalogVpsIndexRoute
  DashboardDashboardPostsCategoriesIndexRoute: typeof DashboardDashboardPostsCategoriesIndexRoute
  DashboardDashboardPostsNewIndexRoute: typeof DashboardDashboardPostsNewIndexRoute
  DashboardDashboardPostsPlatformsIndexRoute: typeof DashboardDashboardPostsPlatformsIndexRoute
  DashboardDashboardUsersUserIdIndexRoute: typeof DashboardDashboardUsersUserIdIndexRoute
  DashboardDashboardUsersRolesIndexRoute: typeof DashboardDashboardUsersRolesIndexRoute
  DashboardDashboardCatalogHostingIdIndexRoute: typeof DashboardDashboardCatalogHostingIdIndexRoute
  DashboardDashboardCatalogHostingNewIndexRoute: typeof DashboardDashboardCatalogHostingNewIndexRoute
  DashboardDashboardCatalogPhysicalIdIndexRoute: typeof DashboardDashboardCatalogPhysicalIdIndexRoute
  DashboardDashboardCatalogPhysicalNewIndexRoute: typeof DashboardDashboardCatalogPhysicalNewIndexRoute
  DashboardDashboardCatalogProxyIdIndexRoute: typeof DashboardDashboardCatalogProxyIdIndexRoute
  DashboardDashboardCatalogViaIdIndexRoute: typeof DashboardDashboardCatalogViaIdIndexRoute
  DashboardDashboardCatalogVpsIdIndexRoute: typeof DashboardDashboardCatalogVpsIdIndexRoute
  DashboardDashboardCatalogVpsNewIndexRoute: typeof DashboardDashboardCatalogVpsNewIndexRoute
  DashboardDashboardPostsPostIdEditIndexRoute: typeof DashboardDashboardPostsPostIdEditIndexRoute
  DashboardDashboardCatalogHostingIdEditIndexRoute: typeof DashboardDashboardCatalogHostingIdEditIndexRoute
  DashboardDashboardCatalogPhysicalIdEditIndexRoute: typeof DashboardDashboardCatalogPhysicalIdEditIndexRoute
  DashboardDashboardCatalogProxyIdEditIndexRoute: typeof DashboardDashboardCatalogProxyIdEditIndexRoute
  DashboardDashboardCatalogViaIdEditIndexRoute: typeof DashboardDashboardCatalogViaIdEditIndexRoute
  DashboardDashboardCatalogVpsIdEditIndexRoute: typeof DashboardDashboardCatalogVpsIdEditIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardForbiddenRoute: DashboardDashboardForbiddenRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDashboardAuditLogsIndexRoute: DashboardDashboardAuditLogsIndexRoute,
  DashboardDashboardMediaIndexRoute: DashboardDashboardMediaIndexRoute,
  DashboardDashboardPostsIndexRoute: DashboardDashboardPostsIndexRoute,
  DashboardDashboardSettingsIndexRoute: DashboardDashboardSettingsIndexRoute,
  DashboardDashboardUsersIndexRoute: DashboardDashboardUsersIndexRoute,
  DashboardDashboardCatalogProxyNewRoute:
    DashboardDashboardCatalogProxyNewRoute,
  DashboardDashboardCatalogViaNewRoute: DashboardDashboardCatalogViaNewRoute,
  DashboardDashboardAppearanceMenuIndexRoute:
    DashboardDashboardAppearanceMenuIndexRoute,
  DashboardDashboardCatalogHostingIndexRoute:
    DashboardDashboardCatalogHostingIndexRoute,
  DashboardDashboardCatalogPhysicalIndexRoute:
    DashboardDashboardCatalogPhysicalIndexRoute,
  DashboardDashboardCatalogProvidersIndexRoute:
    DashboardDashboardCatalogProvidersIndexRoute,
  DashboardDashboardCatalogProxyIndexRoute:
    DashboardDashboardCatalogProxyIndexRoute,
  DashboardDashboardCatalogViaIndexRoute:
    DashboardDashboardCatalogViaIndexRoute,
  DashboardDashboardCatalogVpsIndexRoute:
    DashboardDashboardCatalogVpsIndexRoute,
  DashboardDashboardPostsCategoriesIndexRoute:
    DashboardDashboardPostsCategoriesIndexRoute,
  DashboardDashboardPostsNewIndexRoute: DashboardDashboardPostsNewIndexRoute,
  DashboardDashboardPostsPlatformsIndexRoute:
    DashboardDashboardPostsPlatformsIndexRoute,
  DashboardDashboardUsersUserIdIndexRoute:
    DashboardDashboardUsersUserIdIndexRoute,
  DashboardDashboardUsersRolesIndexRoute:
    DashboardDashboardUsersRolesIndexRoute,
  DashboardDashboardCatalogHostingIdIndexRoute:
    DashboardDashboardCatalogHostingIdIndexRoute,
  DashboardDashboardCatalogHostingNewIndexRoute:
    DashboardDashboardCatalogHostingNewIndexRoute,
  DashboardDashboardCatalogPhysicalIdIndexRoute:
    DashboardDashboardCatalogPhysicalIdIndexRoute,
  DashboardDashboardCatalogPhysicalNewIndexRoute:
    DashboardDashboardCatalogPhysicalNewIndexRoute,
  DashboardDashboardCatalogProxyIdIndexRoute:
    DashboardDashboardCatalogProxyIdIndexRoute,
  DashboardDashboardCatalogViaIdIndexRoute:
    DashboardDashboardCatalogViaIdIndexRoute,
  DashboardDashboardCatalogVpsIdIndexRoute:
    DashboardDashboardCatalogVpsIdIndexRoute,
  DashboardDashboardCatalogVpsNewIndexRoute:
    DashboardDashboardCatalogVpsNewIndexRoute,
  DashboardDashboardPostsPostIdEditIndexRoute:
    DashboardDashboardPostsPostIdEditIndexRoute,
  DashboardDashboardCatalogHostingIdEditIndexRoute:
    DashboardDashboardCatalogHostingIdEditIndexRoute,
  DashboardDashboardCatalogPhysicalIdEditIndexRoute:
    DashboardDashboardCatalogPhysicalIdEditIndexRoute,
  DashboardDashboardCatalogProxyIdEditIndexRoute:
    DashboardDashboardCatalogProxyIdEditIndexRoute,
  DashboardDashboardCatalogViaIdEditIndexRoute:
    DashboardDashboardCatalogViaIdEditIndexRoute,
  DashboardDashboardCatalogVpsIdEditIndexRoute:
    DashboardDashboardCatalogVpsIdEditIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface authVerifyEmailRouteChildren {
  authVerifyEmailConfirmRoute: typeof authVerifyEmailConfirmRoute
}

const authVerifyEmailRouteChildren: authVerifyEmailRouteChildren = {
  authVerifyEmailConfirmRoute: authVerifyEmailConfirmRoute,
}

const authVerifyEmailRouteWithChildren = authVerifyEmailRoute._addFileChildren(
  authVerifyEmailRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
